### ISSUE TITLE
RequestsLibrary missing in Container

### ISSUE THREAD

**Issue by Jicmou** [ppodgorsek/docker-robot-framework#108]
# Bug report / Feature request

## 1. Environment:

Used `ppodgorsek.docker-robot-framework:latest` (currently 3.2.0)

## 2. Steps to reproduce

In your Test Suite, Have a test needing RequestsLibrary, e.g:
```
*** Settings ***
Library   RequestsLibrary

*** Test Cases ***
Test Session Creation
    [Arguments]    ${SESSION_NAME}    ${URL}
    Create Session    ${SESSION_NAME}    ${URL}
```
## 3. Expected Result

The test executes.

##  4. Actual Result

We get the following error:
```
[ ERROR ] Error in file '[FILE_PATH]': Importing test library 'RequestsLibrary' failed: ImportError: No module named RequestsLibrary
```

I'm preparing a PR to fix this issue ;)
The resolution will be to install `robotframework-requests`

**Comment by ppodgorsek** [comment]
Could you add the link to the Requests project in this ticket please? I would like to read more about it to understand its benefits.

**Comment by ppodgorsek** [comment]
Done
