### ISSUE TITLE
Importing Dialogs failes with ImportError: No module named tkinter

### ISSUE THREAD

**Issue by strayobject** [ppodgorsek/docker-robot-framework#158]
I seem to be unable to use Dialogs due to the error below.
Please note that I'm new to Robot and it might not be an issue with your docker image.
Nevertheless it would be nice to know. Thanks.

```
[ ERROR ] Error in file '/opt/robotframework/tests/my_tests.robot': Importing test library 'robot.libraries.Dialogs' failed: ImportError: No module named tkinter
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/robot/libraries/Dialogs.py", line 39, in <module>
    from .dialogs_py import MessageDialog, PassFailDialog, InputDialog, SelectionDialog, MultipleSelectionDialog
  File "/usr/lib/python2.7/site-packages/robot/libraries/dialogs_py.py", line 24, in <module>
    from tkinter import (Button, Entry, Frame, Label, Listbox, TclError,
PYTHONPATH:
  /usr/bin
  /usr/lib/python27.zip
  /usr/lib64/python2.7
  /usr/lib64/python2.7/plat-linux2
  /usr/lib64/python2.7/lib-tk
  /usr/lib64/python2.7/lib-old
  /usr/lib64/python2.7/lib-dynload
  /usr/lib64/python2.7/site-packages
  /usr/lib/python2.7/site-packages
```

Found this onstackoverflow: https://stackoverflow.com/questions/27429367/assertionerror-importing-test-library-dialogs-failed-importerror-no-module

**Comment by ppodgorsek** [comment]
As its name implies, Dialogs allows Python to display dialog boxes to the end user.
This Robot project was designed to run in a headless manner, which means no user interaction is possible by default.

You could extend the image, add Dialogs and run it by connecting to the relevant socket to display the output screen but I would first of all check whether you really need Dialogs or not.

**Comment by strayobject** [comment]
Ah, right, thank you :smile:
