### ISSUE TITLE
Gitlab CI/CD using Robert Framework and Docker

### ISSUE THREAD

**Issue by kazisajid786** [ppodgorsek/docker-robot-framework#159]
I am new to Gitlab and Robert framework. Currently i have referred this link (https://www.digitalocean.com/community/tutorials/how-to-build-docker-images-and-host-a-docker-image-repository-with-gitlab) and accessed our website via localhost. Earlier i used to run automation for website from robot framework code via command line specifying csv filepath. Now i want to perform CI/CD for the website in gitlab using docker and Robert framework. Can you please help me understand what should be inside the test folder and how to bind our test cases(csv file) to test folder and robot code to perform CI/CD

**Comment by ppodgorsek** [comment]
Could you send an example of command line and CSV file you used previously please?
Were you using a specific library to load your tests, such as https://github.com/s4int/robotframework-CSVLibrary ?

**Comment by kazisajid786** [comment]
Hi thank you for replying, Through command prompt i used to run as, Robot -- variable TestFilePath : filename.csv main.Robot. Here i had used CSVLibrary. I used to go to specific folder containing the csv file, the folder included robot framework code for automation.
Example code:
*** Settings ***
Library           Collections
Library           CSVLibrary

*** Test Cases ***
MainModule
    @{testCases}=    Read Csv File To List    ${testFilePath}
    Open Browser   ${WebSitePath}    ${BrowserName}

**Comment by ppodgorsek** [comment]
CSVLibrary is not part of this project, this is why your tests cannot be executed.
You will have to fork this project, add the CSVLibrary then run your tests using the commands provided in the README file.

I might be missing something but, in the example you provided, I don't understand why you actually need the CSVLibrary. Couldn't you simply run your tests in a standard way without `@{testCases}=...`?

**Comment by kazisajid786** [comment]
Thank you, actually i am new and fresher to Robert framework may be i am missing something, actually i am not running this project, i am using this as reference for our project. Above code i mentioned was just a part of complete code. Due to restrictions i may not be able to share complete code. I have a csv file which contains test cases just like the one you mentioned  in data.csv (Examples folder). I am facing two issues right now,
1) Everytime i commit changes in gitlab, it reinstalls libraries such as (csvlibrary, collections etc) chrome, robert framework also gets reinstalled which is time consuming(RUN pip install robot framework is how i installed), can you help to avoid reinstalling on this.
 2) How to bind csv filepath to robert framework, to run it through docker.

**Comment by ppodgorsek** [comment]
It is normal that GitLab reinstalls libraries if you are not running in Docker, as it recreates new VMs.

As mentioned in my previous message, you will have to fork this project, add the CSVLibrary then run your tests using the commands provided in the README file.
Once the libraries are in your Docker image, GitLab won't have to install them, it will just download the correct Docker image from the Docker Hub. (assuming that's where you push it)

Regarding the CSV file path, mount it as a separate volume in your new Docker image and make sure it points to the correct mounted folder.
You can use `-e ROBOT_OPTIONS="--variable testFilePath=changeme"` if needed when running the Docker image.

**Comment by kazisajid786** [comment]
Thank You for helping me out, cleared my doubts, will work on this.

**Comment by ppodgorsek** [comment]
Closing this issue, as it doesn't require any changes to the project itself.
