### ISSUE TITLE
Alpine-based version

### ISSUE THREAD

**Issue by UltimateDogg** [ppodgorsek/docker-robot-framework#162]
i took a few hours and ported this work to [alpine base os]( https://github.com/UltimateDogg/docker-robot-framework/tree/alpine), and it seems to remove about 200 MB from the image size and that is just my preliminary work. you can see the sizes [here](https://microbadger.com/images/ultimatedogg/docker-robot-framework:alpine) vs [here](https://microbadger.com/images/ppodgorsek/robot-framework). I confirmed on my local that it runs at lest some selenium tests but i didnt run the full test suuite yet. Is there interest in moving this direction?

**Comment by ppodgorsek** [comment]
Let's wait a bit for this one...
https://www.zdnet.com/article/alpine-linux-docker-images-ship-a-root-account-with-no-password/

**Comment by UltimateDogg** [comment]
i did see that, https://threatpost.com/alpine-linux-docker-images-unlocked/144542/

> The impact of the bug may be limited, according to some users chiming in on GitHub. One such user, Tianon Gravi, pointed out: “No currently supported Alpine images are affected (all affected images are [end of life]), the attack vector is very narrow to begin with, and there are a couple other images we’re looking to fix (and updating our test to catch this more aggressively).”
but we should be cautious.

what UI tools do you want to check?

**Comment by ppodgorsek** [comment]
About the UI tools, I mean applications - such as browsers - relying on a set of dependencies for which Alpine doesn't always provide the official version. From the top of my head, glibc and libstdc++ are examples of such custom packages in Alpine if I remember well.

Graphical applications are not the only applications which can be impacted by those libraries but until now the issues I came across were always in such applications. I want to avoid introducing issues because of this, that's why I'd like to do more research first. (maybe those issues have been resolved since, I had problems a while back with the older versions of Alpine)

This task could also be a good excuse to write more automated tests for the project.

**Comment by UltimateDogg** [comment]
There are many examples of chrome used now for similar stuff to what we are doing [(example)](https://damianhodgkiss.com/articles/how-to-run-google-chrome-headless-and-nodejs-in-a-docker-container/) and even googles official tool puppeteer can work with it. Since the big difference of alpine is the muslc lib, if there is a recompiled port for it you it should mostly work, but early on there were a lot of missing packages. 

Still its a large change (on the level of a major version) so I agree its not something to rush. I will look at seeing what tests are there and what extra tests would be needed to cover a good range of functionality

**Comment by Noordsestern** [comment]
There is a maintained base image for robot framework in alpine: https://github.com/asyrjasalo/rfdocker
Maybe you like to build ui-tooling, webdrivers and browsers on top of that.

**Comment by UltimateDogg** [comment]
i had looked at that, but he adds it as an entry point directly so it has to be overwritten anyway and all he does besides that is base it off the same base image (alpine python) as i do. it also it uses args vs env files that we use but i think args may be more appropriate. I may try and base, i have to update this to have python 3 anyway.

**Comment by Noordsestern** [comment]
It was only an idea.

I was thinking that `docker-robot-framework` is virtually an extension of a robotframework base image extended by webdrivers, browsers and robotframework-seleniumlibrary. Maybe it would be worthwhile combining forces and provide an `rfdocker-selenium` image. 

But as I said, only an idea.

**Comment by UltimateDogg** [comment]
thats interesting idea, i can see whats applicable to robot in general from here and then see if they can be pushed there

**Comment by ppodgorsek** [comment]
Extending the other project https://github.com/asyrjasalo/rfdocker was not adding any benefit, only an unnecessary dependency.
The image has therefore been based directly on the Alpine one.
