### ISSUE TITLE
When i execute cases with resource file i am getting "Resource file  does not exist" error message.

### ISSUE THREAD

**Issue by Cerosh** [ppodgorsek/docker-robot-framework#163]
When i execute cases with resource file i am getting "Resource file  does not exist" error message. I have given the folder structure of resource and test files. I have also attached the log of the first execution which went successful but without a resource file and the second execution which failed with the resource file.

Resource files are located in the location given below
project_name/resources/common/resource_file.robot

tests are located in the location given below
project_name/Tests/suite_name/test1.robot

```
ceroshjacobs$ docker run \
>     -v `pwd`/reports:/opt/robotframework/reports:Z \
>     -v `pwd`/suite_name:/opt/robotframework/tests:Z \
>     ppodgorsek/robot-framework:latest
```
==============================================================================
Tests                                                                         
==============================================================================
Tests.0 Suite One                                                             
==============================================================================
This Test Case Does No Operation                                      | PASS |
------------------------------------------------------------------------------
This Test Case Will Launch A Browser                                  | PASS |
------------------------------------------------------------------------------
Tests.0 Suite One                                                     | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Tests                                                                 | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /opt/robotframework/reports/output.xml
Log:     /opt/robotframework/reports/log.html
Report:  /opt/robotframework/reports/report.html

**Second Execution**
```
ceroshjacobs$
 docker run \
>     -v `pwd`/reports:/opt/robotframework/reports:Z \
>     -v `pwd`/docker_execution:/opt/robotframework/tests:Z \
>     ppodgorsek/robot-framework:latest
```
==============================================================================
Tests                                                                         
==============================================================================
[ ERROR ] Error in file '/opt/robotframework/tests/fund_transfer_WebsiteTest.robot': Resource file '../../Resources/Common/LogIn/LogIn.robot' does not exist.
[ ERROR ] Error in file '/opt/robotframework/tests/fund_transfer_WebsiteTest.robot': Resource file '../../Resources/Common/LogIn/BrowserLogIn.robot' does not exist.
[ ERROR ] Error in file '/opt/robotframework/tests/fund_transfer_WebsiteTest.robot': Resource file '../../Resources/Common/LogOff.robot' does not exist.
[ ERROR ] Error in file '/opt/robotframework/tests/fund_transfer_WebsiteTest.robot': Resource file '../../Resources/Common/High_Level_keywords.robot' does not exist.
[ ERROR ] Error in file '/opt/robotframework/tests/fund_transfer_WebsiteTest.robot': Resource file '../../Resources/Common/User_Creds.robot' does not exist.

**Comment by UltimateDogg** [comment]
assuming pwd project_name/Tests/ then you are not passing the resources in as a volume so docker cant see them, consequently in the container ../../Resources/Common/User_Creds.robot is /opt/Resources/Common/User_Creds.robot which doesnt exist, and infact that does not exist. Try passing project_name in as the volume for tests (although would have to see your full structure to say for sure).

**Comment by Cerosh** [comment]
yes i had to mount the resource folder and it resolved my issue hence closing it.
--mount type=bind,source=`pwd`/robot_framework_docker/resource,target=/opt/robotframework/resource \
