### ISSUE TITLE
Docker tag for 3.3.0

### ISSUE THREAD

**Issue by UltimateDogg** [ppodgorsek/docker-robot-framework#173]
can you make a tagged 3.3.0 version in docker hub? that would allow people to get latest changes without worrying about changing builds

**Comment by ppodgorsek** [comment]
Unfortunately, tag 3.3.0 on GitHub cannot be built, as Firefox 66.0 cannot be resolved during build anymore. I would have to update Firefox on tag 3.3.0 and create a new tag 3.3.1.
I don't think this would add much value.

**Comment by UltimateDogg** [comment]
Ok the last tag was just old so i picked 3.3.0. you can setup docker hub to do the tagging right when tags are created in github

**Comment by ppodgorsek** [comment]
The automatic build of tags on Docker Hub is already set up. I might simply build locally with Firefox 67 and push to the Hub in order to have the 3.3.0 image anyway.

**Comment by UltimateDogg** [comment]
yeah ok i see now on docker hub, i am fine with a 3.3.1 image instead - whatevers easier

**Comment by ppodgorsek** [comment]
New release 3.3.1 created and available on the Docker Hub.
