### ISSUE TITLE
Is there a difference between xvfb-run and headless browser?

### ISSUE THREAD

**Issue by Noordsestern** [ppodgorsek/docker-robot-framework#175]
I saw that tests can be launch by running `run-tests-in-virtual-screen.sh` which simulates an X-server.

Is there a difference between (1) running a solid firefox in xvfb and (2) running an headlessfirefox?

**Comment by ppodgorsek** [comment]
There is no major difference between both, simply different approaches.

Using xvfb allows to manage screen options / window sizes in a more standard approach for all browsers without requiring to pass specific arguments in the test cases, as parameter names such as window size will likely vary between browsers.

**Comment by Noordsestern** [comment]
Thank you!
