### ISSUE TITLE
For DatabaseLibrary which DB driver does this support

### ISSUE THREAD

**Issue by humbienri** [ppodgorsek/docker-robot-framework#193]
Hello,

In notice that this image installs/contains the RobotFramework-DatabaseLibrary but which DBs or DB drivers does it support?  For example, `pymssql` for accessing MS SQL Server databases?

Thank you for your time!

**Comment by UltimateDogg** [comment]
by default we dont install any, but you can do pip install of the one you want. robot-dblib supports any DB API spec 2 packages

**Comment by humbienri** [comment]
Thanks! Yeah I'm cutting my teeth on Docker using your image as a starting point.  Thank you for that!

I am also struggling with installing `pymssql` on it.  Gonna try a base alpine image to see if I have the same heartache.

I was ableo to install `pyodbc' on your image, along with the required `unixodbc` as well but when it comes to actual run time I does not work.  Complains about a missing `*.so` file so I think I may still need to do some moving/copying of files around.

Again, thank you all.

**Comment by ppodgorsek** [comment]
I hope you'll soon manage to find where the issue comes from. If you add the steps/resolution here, they could be added to a specific section in the readme file, in case other need it.

**Comment by ppodgorsek** [comment]
The Troubleshooting section of the README has been updated with information about database testing.
