### ISSUE TITLE
Update geckodriver to 0.26

### ISSUE THREAD

**Issue by ppawel** [ppodgorsek/docker-robot-framework#216]
We are seeing some intermittent failures with messages like `WebDriverException: Message: Failed to decode response from marionette` - this could be improved in latest geckodriver.

See https://github.com/mozilla/geckodriver/releases, specifically:

> Connection attempts to Firefox made more reliable
> 
> geckodriver now waits for the Marionette handshake before assuming
> the session has been established. This should improve reliability
> in creating new WebDriver sessions.
>

**Comment by ppawel** [comment]
I made a fork of this repository and updated to 0.26 myself but note that it requires installing glibc in the container, basically this:

https://wiki.alpinelinux.org/wiki/Running_glibc_programs

Resulting image is quite heavy and I guess it is kind of nullifying the benefit of using Alpine, could just as well switch (back?) to Ubuntu or Fedora...?

**Comment by UltimateDogg** [comment]
I dont think you should need to install glibc to run it, but adding glibc would indeed make it huge.

**Comment by ppawel** [comment]
Version 0.26 does not work without glibc, see the above linked SO thread, I saw exactly the same problems.

Version 0.22 worked fine. I don't know if they changed something or Alpine changed something in the mean time but in any case 0.26 does not work.

**Comment by UltimateDogg** [comment]
sorry, i didnt see the stackoverflow link when i read it. There are other issues where people are using geckodriver with musl and that team has been willing to provide a fix so we would probably have to get some logs and open a defect there. Does geckodriver from source work if compiled against musl?

**Comment by ppawel** [comment]
Now you can see it in your CI run: https://travis-ci.org/ppodgorsek/docker-robot-framework/builds/612292453#L900

I have not had the time to build it from source, might try it and report back here. For now the glibc package works fine, I can live with the image size increase, it is not ideal but well...

**Comment by ppodgorsek** [comment]
This enhancement has been done, along with the introduction of the glibc dependency, as it is important to keep this project as stable and reliable as possible, hence why the geckodriver upgrade was required.

While checking on the Docker Hub, it looks like the image size increased only very slightly. (4 MB)
