### ISSUE TITLE
Add variable to mount the directories for tests and reports

### ISSUE THREAD

**Issue by wazowsk1** [ppodgorsek/docker-robot-framework#229]
Is it possible to make ```/opt/robotframework/tests``` and ```/opt/robotframework/reports``` variable?

I would like to use this image in my jenkins build and the default mount directory is not in ```/opt/robotframework/```. For my build to work a relative path of ```tests``` and ```reports``` is required.

**Comment by UltimateDogg** [comment]
does `docker run -v ../reports:/opt/robotframework/reports:Z -v ../tests:/opt/robotframework/tests:Z ppodgorsek/robot-framework:latest` not let you do that? Or are you asking to allow this image to be rebuilt with the items in a different path?

**Comment by wazowsk1** [comment]
When using Jenkins pipeline for docker:  https://jenkins.io/doc/book/pipeline/docker/

Jenkins will start a new docker container with the specified image per stage and auto mounts the Jenkins workspace which contains the source code (in this case the robot tests) and sets the docker container workspace to that path. This path can be different for each Jenkins job and or branch.

The following example will work since the xvfb command is specified with the relative paths for reports and tests, but I would prefer just calling "./run-tests-in-virtual-screen.sh" instead and specify the paths as an environment variable
```
        stage('Tests') {
            agent  {
                docker {
                    image 'ppodgorsek/robot-framework:3.5.0'
                    args '--shm-size=1g -e BROWSER=chrome'
                }
            }
            steps {
                sh 'xvfb-run --server-args="-screen 0 ${SCREEN_WIDTH}x${SCREEN_HEIGHT}x${SCREEN_COLOUR_DEPTH} -ac" robot --outputDir reports --loglevel DEBUG tests'
            }
            post {
                always {
                    robot 'reports'
                }
            }
        }
```
Logging of jenkins job to illustrate the above stage configuration
```
18:05:56  [Pipeline] withDockerContainer
18:05:56  dockeragent-0f98805f seems to be running inside container f6f601ea20b3e9b8d0d8bba1615c7226f65bee0a5c7eb49450ea37f27697f62a
18:05:56  $ docker run -t -d -u 1000:1000 --shm-size=1g -e BROWSER=chrome -w /jenkins/workspace/my-jenkins-job --volumes-from f6f601ea20b3e9b8d0d8bba1615c7226f65bee0a5c7eb49450ea37f27697f62a ppodgorsek/robot-framework:3.5.0 cat
18:05:57  $ docker top a6a1f44e1afb85b51e40a0be98818445c309f503e6ce0eafc798c7080d21a811 -eo pid,comm
18:05:58  [Pipeline] {
18:05:58  [Pipeline] sh
18:05:58  + xvfb-run '--server-args=-screen 0 1920x1080x24 -ac' robot --outputDir reports --loglevel DEBUG tests
18:05:59  ==============================================================================
18:05:59  Tests                                                                         
18:05:59  ==============================================================================
18:05:59  name of test                                                       
18:05:59  ==============================================================================
18:06:00  description of test | FAIL |
```

**Comment by UltimateDogg** [comment]
ok let me look at making the tests input paramerized

**Comment by ChitraLekhaBHeemana** [comment]
Was are also looking for this option to Prametrize the tests that needs to be run AND mount the PROJECT itself(instead of Just TestFolder)
My Scenario: TestSuits and Resources are in Different Folder s .i.e,Resources are outside of TestSuits Folder .
Run Issue: 
when we Mount TestSuits Folder , it cannot find Resources.
And when we mount Whole Project , it is trying to run everything.

**Comment by ppodgorsek** [comment]
Done
