### ISSUE TITLE
Do not use root user in container

### ISSUE THREAD

**Issue by wazowsk1** [ppodgorsek/docker-robot-framework#230]
This image should not use root as user in the container for security reasons.

For example, can we add a user like this?
```
RUN addgroup -S robot && \
  adduser -S robot -G robot
USER robot
WORKDIR /home/robot
```

**Comment by wazowsk1** [comment]
I was testing myself, but xvfb doesn't like to start as non root user.

```_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root```

I will do some more testing, if I can get xvfb to work without root.

**Comment by UltimateDogg** [comment]
Closed #231

**Comment by ppodgorsek** [comment]
The pull request which was merged breaks previously merged code. Reverting the PR merge and reopening this ticket.

**Comment by ppodgorsek** [comment]
This issue should be fixed using User Remapping: https://docs.docker.com/engine/security/userns-remap/

**Comment by wazowsk1** [comment]
what is not working as it should? do you have an example? Can we add a test to Travis?

**Comment by ppodgorsek** [comment]
By doing this change, any existing user of the project would have their tests failing if they are not using a user with the same GUID. I am also unsure of which GUID the new "robot" user is assigned.
The GUID is what matters when managing users in Docker, as they map to users on the host.

Remapping is the most flexible approach which covers all possible use cases and, even better, is an OOTB Docker feature which does not need to be maintained in this project.

I will add documentation to the README explaining how to use it.

**Comment by ppodgorsek** [comment]
Sorry for the delay, pull request #276 has been opened and is based on the work done in PR #231. Thank you @wazowsk1 for the initial work, there was very little missing from it!

The remaining permissions have been fixed and no new user is created unnecessarily. Any user can be set on the command line, including a user not defined on the host nor in the image.
The README file has also been updated accordingly with security considerations.

**Comment by diogofscmariano** [comment]
hi @ppodgorsek. trying to use these changes on my side. will you update the docker hub latest with this fix?

**Comment by ppodgorsek** [comment]
Thank you for letting me know @diogofscmariano !

The Docker Hub build should be automatically triggered every time there is a merge to the master branch.

Strangely, the last builds were all blocked and pending in the Docker Hub. I cancelled them and triggered it again, the latest tag now contains this fix.

**Comment by diogofscmariano** [comment]
> Thank you for letting me know @diogofscmariano !
> 
> The Docker Hub build should be automatically triggered every time there is a merge to the master branch.
> 
> Strangely, the last builds were all blocked and pending in the Docker Hub. I cancelled them and triggered it again, the latest tag now contains this fix.

Thanks for the quick reply. I will try it on my side

**Comment by diogofscmariano** [comment]
> > Thank you for letting me know @diogofscmariano !
> > The Docker Hub build should be automatically triggered every time there is a merge to the master branch.
> > Strangely, the last builds were all blocked and pending in the Docker Hub. I cancelled them and triggered it again, the latest tag now contains this fix.
> 
> Thanks for the quick reply. I will try it on my side

Fixed! I will keep an eye and point to the release once that is out! Thanks once again
