### ISSUE TITLE
Add variable to set Pabot options

### ISSUE THREAD

**Issue by krizm** [ppodgorsek/docker-robot-framework#244]
When running tests in parallel using `ROBOT_THREADS`, it would be good to be able to also set additional `pabot` options (like `--testlevelsplit`, or `--ordering`).
It could be done by adding `PABOT_OPTIONS` variable to the pabot command.

One thing I am sure about is whether or not to move the `--verbose` option to the variable (as default value).

I will try to follow up with a pull request for this soon.

**Comment by ppodgorsek** [comment]
Done
