### ISSUE TITLE
How to add DataDriver Library

### ISSUE THREAD

**Issue by furlanrb** [ppodgorsek/docker-robot-framework#246]
Is it possible to add the datadriver library to robot framework read variables from xls and csv files?
The command is:
pip install --upgrade robotframework-datadriver[XLS]

How is possible to do that?

Thank you.

**Comment by Noordsestern** [comment]
Depends on your environment. You may build a new docker image based on this one and add `pip install --upgrade robotframework-datadriver` to the dockerfile.

**Comment by furlanrb** [comment]
Hey, Noordsestern. Thank you for your answer. Yes, I will try to build a new image adding the datadriver in dockerfile. I am a begginer in containers so I didn't know the steps, but now I got it. Thanks again.

**Comment by furlanrb** [comment]
@Noordsestern man, I tried to build a new container, But I'm getting a lot of errors on the process. Do I need some essentials packages to do it? I'm using CentOS 8.0.

**Comment by UltimateDogg** [comment]
Solution in #312, adding to main image with https://github.com/ppodgorsek/docker-robot-framework/pull/315
