### ISSUE TITLE
Imap library error

### ISSUE THREAD

**Issue by mounamazhoudi** [ppodgorsek/docker-robot-framework#261]
Hello, 

I am a beginner with Docker and I am trying to use this image to run my tests on it.  But I have an issue with the Imap library :  "'quoted-printable' is not a text encoding". I did fix this problem  by editing the "init" file of IMAP Libarry on my local environment, but I don't know how can I do it on docker. Thank you

**Comment by ppodgorsek** [comment]
Hello @mounamazhoudi ,
You can fix this by extending the Docker image and do your fix.
Alternatively, I would suggest to create a pull request for the imap project in order to get it fixed.

**Comment by VyacheslavProtsiuk** [comment]
@mounamazhoudi Hi,

You can use updated a fork for IMAP tests - https://pypi.org/project/robotframework-imaplibrary2/
So, you can update the `robotframework-imaplibrary` to the `robotframework-imaplibrary2` in the Dockerfile.

**Comment by ppodgorsek** [comment]
Thank you @VyacheslavProtsiuk for the link, I updated the library in this project.
@mounamazhoudi could you check with the latest image if your issue is solved please?

**Comment by ppodgorsek** [comment]
Closing this ticket due to inactivity. The IMAP library was updated.
