### ISSUE TITLE
Error Conflit python3 and firefox 74

### ISSUE THREAD

**Issue by yohandion** [ppodgorsek/docker-robot-framework#268]
Hi

I try to build the image and during the build I have a strange error.
To do that I only clone the repo launch:
`docker build .`

Like if Firefox and python wasn't compatible anymore.

```
ERROR: unsatisfiable constraints:
  libffi-3.2.1-r6:
    conflicts: libffi-3.3-r1
    satisfies: libffi-dev-3.2.1-r6[libffi=3.2.1-r6]
               glib-2.60.4-r0[so:libffi.so.6]
               wayland-libs-client-1.17.0-r0[so:libffi.so.6]
               p11-kit-0.23.16.1-r0[so:libffi.so.6]
               .python-rundeps-20200311.011300[so:libffi.so.6]
  libffi-3.3-r1:
    conflicts: libffi-3.2.1-r6
    breaks: libffi-dev-3.2.1-r6[libffi=3.2.1-r6]
    satisfies: firefox-75.0-r1[so:libffi.so.7]
  firefox-75.0-r1:
    breaks: world[firefox~74.0]
```

Someone have this error and how I can solve it ?

**Comment by ppodgorsek** [comment]
I also had a similar issue this morning while trying to upgrade the Firefox version to 75.0. It seems there is a dependency conflict on the repo.
From past experience, this usually gets resolved after a couple of hours, sometimes a day or two. (depends on the Alpine repo maintainers)

**Comment by yohandion** [comment]
Ok thanks isn't me :D 

Just for information, I have try to workaround  and installer firefox-esr but in this case there are conflit with chromnium :D

Just for know why not instal firefox-esr ?

**Comment by hansehv** [comment]
I also have this conflict (today), so not solved yet.  I have been able to build successfully with Firefox 75.0 before this libffi conflict appeared. Can't comment on Firefox 75.0 functioning however, as I run tests with Chromium.

**Comment by ppodgorsek** [comment]
The issue is still occurring, I did some analysis and created an issue in the Python Docker image project: https://github.com/docker-library/python/issues/469

**Comment by ppodgorsek** [comment]
Done in PR #267 by switching to the Alpine 11 repos (same as the base Python image) + Firefox ESR.
