### ISSUE TITLE
a

### ISSUE THREAD

**Issue by awasall** [ppodgorsek/docker-robot-framework#288]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Robot template**
Any Robot template which could help reproduce the issue.

**Screenshots**

**Please provide any relevant information, such as:**

**Additional context**

**Comment by awasall** [comment]
Bonjour en fait j'aimerai savoir quels sont les paramètres à exposer  pour intégrer nos TA dans la chaîne de Dev

**Comment by UltimateDogg** [comment]
did you read the section of the readme titled [Continuous Integration?](https://github.com/ppodgorsek/docker-robot-framework/blob/master/README.md#continuous-integration)

**Comment by awasall** [comment]
Oui je l'ai lu biensur et j'ai regardé dans la partie intégration continue mais c'est le $WORKSPACE que j'ai pas compris
