### ISSUE TITLE
Internet Explorer supported by docker Robot Framework image

### ISSUE THREAD

**Issue by jadhavswapnil71** [ppodgorsek/docker-robot-framework#289]
**Internet Explorer supported by docker Robot Framework image**

Currently i am not able to run my robot framework test cases on Internet Explorer browser on Docker.

I cannot find Internet Explorer version under # Dependency versions in docker file.

**Comment by ppodgorsek** [comment]
This project relies on a Linux image but unfortunately Internet Explorer does not have any Linux version, it will therefore not be supported by this project.
However, Microsoft plans to release a Linux version of Edge by the end of the year, we will then consider adding it.
