### ISSUE TITLE
Request to add module named 'PIL' in DockerFile

### ISSUE THREAD

**Issue by jadhavswapnil71** [ppodgorsek/docker-robot-framework#291]
Request to add module named 'PIL' in DockerFile

I think Python Imaging Library  feature may be used in TC functionality for which the warning message 

failed: ModuleNotFoundError: No module named 'PIL' is observed.

**Comment by UltimateDogg** [comment]
Pil does not seem to support python 3 according to their website, so it cpuld not be added. Where does this error come up? Was it with custom modules?

**Comment by jadhavswapnil71** [comment]
We are using PIL in our Python 3.7. Locally on eclipse it is working . So, i think this should be supported.   This error comes when running PIL on docker image.

**Comment by UltimateDogg** [comment]
You get that error because PIL is not in the docker image. You can try adding it by extending the docker image (using this as a base) and then doing a pip install of the PIL library.

**Comment by ppodgorsek** [comment]
I might be missing the value of the PIL but I don't think many people will be using it, hence it would not make sense to increase the image size unnecessarily.
Out of curiosity, could you provide a use case for the Python Imaging Library in Robot Framework please?

**Comment by jadhavswapnil71** [comment]
Hello Paul,

Thanks for writing back to me .. Yes we have extended our docker image
taking your image base and added PIL library.

Thanks,
Swapnil Jadhav
8446544685

**Comment by ppodgorsek** [comment]
Thank you for your confirmation @jadhavswapnil71, closing this ticket.

**Comment by jadhavswapnil71** [comment]
Thanks for the support & Robot docker image to entire Professionals.

Regards,
Swapnil
