### ISSUE TITLE
PYMYSQL library is needed to be added in docker image 3.5 and latest

### ISSUE THREAD

**Issue by jadhavswapnil71** [ppodgorsek/docker-robot-framework#293]
PYMYSQL library is needed to be added in docker image 3.5 and latest.

Error getting :
 
Parent suite setup failed:
ModuleNotFoundError: No module named ‘pymysql’.

**Comment by UltimateDogg** [comment]
we dont actually install any database libraries (since they are large and everyone uses their own). You can extend this docker and do a pip install pymysql and it should work fine

**Comment by ppodgorsek** [comment]
This explanation has been added to the Troubleshooting section of the README.
