### ISSUE TITLE
Can't build image: firefox-esr (missing)

### ISSUE THREAD

**Issue by anttipessa** [ppodgorsek/docker-robot-framework#295]
**Describe the bug**
When trying to build the current Dockerfile locally, the build process fails because of missing firefox-esr. 
Output:

`ERROR: unsatisfiable constraints:
  firefox-esr (missing):
    required by: world[firefox-esr~68]

The command '/bin/sh -c apk update   && apk --no-cache upgrade   && apk --no-cache --virtual .build-deps add     gcc     libffi-dev     linux-headers     make     musl-dev     openssl-dev     which     wget   && apk --no-cache add     "chromium~$CHROMIUM_VERSION"     "chromium-chromedriver~$CHROMIUM_VERSION"     "firefox-esr~$FIREFOX_VERSION"     xauth     "xvfb-run~$XVFB_VERSION"   && mv /usr/lib/chromium/chrome /usr/lib/chromium/chrome-original   && ln -sfv /opt/robotframework/bin/chromium-browser /usr/lib/chromium/chrome   && pip3 install     --no-cache-dir     robotframework==$ROBOT_FRAMEWORK_VERSION     robotframework-databaselibrary==$DATABASE_LIBRARY_VERSION     robotframework-faker==$FAKER_VERSION     robotframework-ftplibrary==$FTP_LIBRARY_VERSION     robotframework-imaplibrary2==$IMAP_LIBRARY_VERSION     robotframework-pabot==$PABOT_VERSION     robotframework-requests==$REQUESTS_VERSION     robotframework-seleniumlibrary==$SELENIUM_LIBRARY_VERSION     robotframework-sshlibrary==$SSH_LIBRARY_VERSION     PyYAML   && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub     && wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$ALPINE_GLIBC/glibc-$ALPINE_GLIBC.apk"     && wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$ALPINE_GLIBC/glibc-bin-$ALPINE_GLIBC.apk"     && apk add glibc-$ALPINE_GLIBC.apk     && apk add glibc-bin-$ALPINE_GLIBC.apk     && rm glibc-$ALPINE_GLIBC.apk     && rm glibc-bin-$ALPINE_GLIBC.apk     && rm /etc/apk/keys/sgerrand.rsa.pub   && wget -q "https://github.com/mozilla/geckodriver/releases/download/$GECKO_DRIVER_VERSION/geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz"     && tar xzf geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz     && mkdir -p /opt/robotframework/drivers/     && mv geckodriver /opt/robotframework/drivers/geckodriver     && rm geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz   && apk del --no-cache --update-cache .build-deps' returned a non-zero code: 1`

**Please provide any relevant information, such as:**
 - OS: Windows 10 Pro
 - Version 1903

**Comment by ppodgorsek** [comment]
Fixed
