### ISSUE TITLE
Change timezone 

### ISSUE THREAD

**Issue by DrVanScott** [ppodgorsek/docker-robot-framework#299]
Currently, the docker container always starts with times relative to UTC.

I use DateTime's Get Current Date (which iteself only supports "local" and UTC), to check some times generated by a web application. The application's timestamps are relative to Europe/Berlin. So while my test PASS if running locally, it fails if running dockerized.

Can docker-robot-framework support tzdata?

Currently i use the following workaround:

    TIMECORR=$(TZ=Europe/Berlin date +%:z | tr '+-' '-+')
    docker run --rm -it -e "TZ=${TIMECORR}" ppodgorsek/robot-framework:latest date

But i assume that this would fail e.g. if tests are running over the moment when CEST changes to CET

**Comment by UltimateDogg** [comment]
does #318 help?

**Comment by DrVanScott** [comment]
Thanks for point me at this. I will give it a try in the next few days and will come back with my findings...

**Comment by ppodgorsek** [comment]
What is the status of this issue? Can it be closed?

**Comment by DrVanScott** [comment]
Yes, sorry, my team switched to rf-browser, so I cannot test any further...
