### ISSUE TITLE
Missing drivers

### ISSUE THREAD

**Issue by mkatrenik** [ppodgorsek/docker-robot-framework#3]
I'm not sure how is this supposed to work, since it doesn't contain selenium drivers?

`WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

`WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

Am I missing something obvious?

**Comment by ppodgorsek** [comment]
The issue was due to the fact that the Docker image was extended in a private image which contained the drivers.
The drivers have been added to this project, and future testing will be done against this project instead of the extended private image.
