### ISSUE TITLE
Rerun failed tests with docker image

### ISSUE THREAD

**Issue by martkiviselg** [ppodgorsek/docker-robot-framework#300]
**Is your feature request related to a problem? Please describe.**
I would like to rerun failed tests using robot's --rerunfailed tag

**Describe the solution you'd like**
At the moment I couldn't find any solution how to provide existing output,xml to new docker run to rerun tests.
All the time I get: No such file or directory error.

**Describe alternatives you've considered**

**Additional context**
How I tried to run this:
```
docker run --shm-size=1g --rm -v /opt/jenkins/jobs/JOB_NAME/workspace:/opt/robotframework/reports:Z \
	-v /opt/jenkins/jobs/JOB_NAME/workspace:/opt/robotframework/tests:Z -e BROWSER=chrome -e ROBOT_THREADS=2 -e PABOT_OPTIONS="--testlevelsplit" \
	-e ROBOT_OPTIONS='--include RegressionANDsmoke --variable local:False' \
   robot-framework-docker    || 

docker run --shm-size=1g --rm -v /opt/jenkins/jobs/JOB_NAME/workspace:/opt/robotframework/reports:Z \
	-v /opt/jenkins/jobs/JOB_NAME/workspace/ui-tests:/opt/robotframework/tests:Z \
    -e BROWSER=chrome -e ROBOT_THREADS=2 -e PABOT_OPTIONS='--testlevelsplit --rerunfailed /opt/robotframework/reports/output.xml -o output2.xml' \
    -e ROBOT_OPTIONS='--variable local:False'     robot-framework-docker

```
And the result is like this:
```
get_suite_names: output_file='/opt/robotframework/reports/pabot_results/suite_names.xml' does not exist
Storing .pabotsuitenames file
No tests to execute
Total testing: 0.0 seconds
Elapsed time:  0.1 seconds
[ ERROR ] Collecting failed tests or tasks from 'output.xml' failed: Reading XML source 'output.xml' failed: No such file or directory

```

**Comment by LerryAlexander** [comment]
Hi @martkiviselg 
I think you are missing the variable $ROBOT_TESTS_DIR in the second docker run execution, so should be able to rerunning tests this way:

`docker run --shm-size=1g --rm -v /opt/jenkins/jobs/JOB_NAME/workspace:/opt/robotframework/reports:Z \
	-v /opt/jenkins/jobs/JOB_NAME/workspace:/opt/robotframework/tests:Z -e BROWSER=chrome -e ROBOT_THREADS=2 -e PABOT_OPTIONS="--testlevelsplit" \
	-e ROBOT_OPTIONS='--include RegressionANDsmoke --variable local:False' \
   robot-framework-docker    || 

docker run --shm-size=1g --rm -v /opt/jenkins/jobs/JOB_NAME/workspace:/opt/robotframework/reports:Z \
	-v /opt/jenkins/jobs/JOB_NAME/workspace/ui-tests:/opt/robotframework/tests:Z \
    -e BROWSER=chrome -e ROBOT_THREADS=2 -e PABOT_OPTIONS='--testlevelsplit --rerunfailed /opt/robotframework/reports/output.xml -o output2.xml' \
    -e ROBOT_OPTIONS='--variable local:False'    $ROBOT_TESTS_DIR  robot-framework-docker`

**Comment by martkiviselg** [comment]
Hi, @LerryAlexander , thanks for the answer. But my main problem is that I cannot access output.xml after the first test execution, docker image itself accepts parameters, but it doesn't understand where to look for failed tests

**Comment by ppodgorsek** [comment]
There seems to be an issue in your commands:
* The first command mounts the test folder onto `/opt/jenkins/jobs/JOB_NAME/workspace`
* The second command mounts the test folder onto `/opt/jenkins/jobs/JOB_NAME/workspace/ui-tests`

How can the failed tests be re-run if Robot does not have access to the same test suites?

**Comment by martkiviselg** [comment]
@ppodgorsek - thanks, your comment made me to try couple more changes. Solution is:
      -e PABOT_OPTIONS='--rerunfailed /opt/robotframework/reports/output.xml -o output2.xml

path to output.xml should be set based on docker reports file, but I tried to set jenkins folder outside docker. 
I guess this thing should be added to documentation. One thing I didn't get yet - merging output files together. Need to try a bit more. I will update this issue If I find solution

**Comment by martkiviselg** [comment]
Managed to get the expected result.
For rebot tool there are 2 options available: robot.rebot  -OPTIONS and rebot -OPTIONS
I have chosen easier option for me - just calling rebot.

But for that purpose I have modified _**Dockerfile**_ and **_bin\run-tests-in-virtual-screen.sh_**
In _**Dockerfile**_file I have added this: 

```
# Option to run rebot tool
ENV REBOT_TOOL 0 
```

and in **_bin\run-tests-in-virtual-screen.sh_**  I had to change a bit more: 
```
`#!/bin/sh

HOME=${ROBOT_WORK_DIR}

if [ $REBOT_TOOL -eq 1 ]
then 
	echo 'rebot started'
    xvfb-run \
        rebot \
        ${ROBOT_OPTIONS} 
	
	echo 'rebot completed'
	break
# No need for the overhead of Pabot if no parallelisation is required

elif [ $ROBOT_THREADS -eq 1 ]
.... continues with original content`
```

To have possibilities to run rebot tool the docker run command should be also modified:

`docker run --shm-size=1g --rm -v %PATH_TO_REPORTS%:/opt/robotframework/reports:Z -e REBOT_TOOL=1 -e REBOT_OPTIONS='-d /opt/robotframework/reports --output /opt/robotframework/reports/output.xml  --merge /opt/robotframework/reports/output*.xml ' robot-framework:latest`

And currently, I have to set output folder aswell, because for some reason it didn't come from  **_bin\run-tests-in-virtual-screen.sh_** file.

`-d /opt/robotframework/reports`

I understand that it's not a very clean solution, but it's working and maybe @ppodgorsek or someone else can a bit more clear solution for that, but this works for my purposes and I hope that might help someone else.

So full flow with rerunning could be like this:
```

docker run --shm-size=1g --rm -v %PATH_TO_REPORTS%:/opt/robotframework/reports:Z \
-v %PATH_TO_TESTS%:/opt/robotframework/tests:Z \
-e REBOT_TOOL=0 -e BROWSER=chrome -e ROBOT_THREADS=2 \
-e PABOT_OPTIONS="--testlevelsplit" -e ROBOT_OPTIONS='  ' robot-framework:latest || 

docker run --shm-size=1g --rm -v %PATH_TO_REPORTS%:/opt/robotframework/reports:Z \
-v %PATH_TO_TESTS%:/opt/robotframework/tests:Z -e REBOT_TOOL=0 \
 -e BROWSER=chrome -e ROBOT_THREADS=2 -e PABOT_OPTIONS="--testlevelsplit" \
-e PABOT_OPTIONS='--rerunfailed /opt/robotframework/reports/output.xml -o output2.xml -' robot-framework:latest ||

docker run --shm-size=1g --rm -v %PATH_TO_REPORTS%:/opt/robotframework/reports:Z \
-e REBOT_TOOL=1 -e REBOT_OPTIONS='-d /opt/robotframework/reports --output /opt/robotframework/reports/output.xml  \
--merge /opt/robotframework/reports/output*.xml ' robot-framework:latest"
```
