### ISSUE TITLE
Update the Selenium Library to version 3.0.0

### ISSUE THREAD

**Issue by ppodgorsek** [ppodgorsek/docker-robot-framework#33]
See https://github.com/robotframework/SeleniumLibrary/releases/tag/v3.0.0

**Comment by ppodgorsek** [comment]
It is important to note that Selenium2Library has been deprecated in favour of SeleniumLibrary.
See https://github.com/robotframework/Selenium2Library

**Comment by ppodgorsek** [comment]
Done

**Comment by ppodgorsek** [comment]
The README file should also be updated.

**Comment by ppodgorsek** [comment]
Done

**Comment by kichooo** [comment]
Hello @ppodgorsek. Thank you for maintaining this dockerhub repo.

One insight - this update might break many builds depending on Selenium2Library - maybe this should be bigger semver change?

**Comment by ppodgorsek** [comment]
@kichooo Indeed, you are right, this is a big change. I will reopen this ticket in order to also change the project's version.

**Comment by ppodgorsek** [comment]
The project version has been updated to 3.1.0 in order to reflect the breaking change introduced by the new Selenium library.
