### ISSUE TITLE
exit code 0 although tests failed

### ISSUE THREAD

**Issue by knecht** [ppodgorsek/docker-robot-framework#330]
**Describe the bug**
run-tests-in-virtual-screen.sh returns the exit code of its last command. 
Since #322 this is no longer the exit code of the test execution, but always exit code 0 (at least as long as you don't upload anything to aws).
Since robot framework returns meaningful exit codes, it would be great if run-tests-in-virtual-screen.sh returned them again.

**To Reproduce**
1. execute a failing test
2. echo $?

**Comment by ppodgorsek** [comment]
This issue has been fixed and merged onto the master branch.
