### ISSUE TITLE
Cannot build image locally

### ISSUE THREAD

**Issue by linh-ngophuochoai** [ppodgorsek/docker-robot-framework#331]
**Describe the bug**
I tried to build image locally using docker build. However, build was failed and giving the following error

#10 181.4   running build_rust
#10 181.4
#10 181.4       =============================DEBUG ASSISTANCE=============================
#10 181.4       If you are seeing a compilation error please try the following steps to
#10 181.4       successfully install cryptography:
#10 181.4       1) Upgrade to the latest pip and try again. This will fix errors for most
#10 181.4          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
#10 181.4       2) Read https://cryptography.io/en/latest/installation.html for specific
#10 181.4          instructions for your platform.
#10 181.4       3) Check our frequently asked questions for more information:
#10 181.4          https://cryptography.io/en/latest/faq.html
#10 181.4       4) Ensure you have a recent Rust toolchain installed:
#10 181.4       5) If you are experiencing issues with Rust for *this release only* you may
#10 181.4          set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
#10 181.4       =============================DEBUG ASSISTANCE=============================
#10 181.4
#10 181.4   error: Can not find Rust compiler
#10 181.4   ----------------------------------------
#10 181.4   ERROR: Failed building wheel for cryptography
#10 181.4   Building wheel for pynacl (PEP 517): started
#10 236.9   Building wheel for pynacl (PEP 517): finished with status 'done'
#10 236.9   Created wheel for pynacl: filename=PyNaCl-1.4.0-cp39-cp39-linux_x86_64.whl size=268333 sha256=d8b76e1613b52df1d1c40a7227bfe87335f149383d9889c8adab7145fedfe922
#10 236.9   Stored in directory: /tmp/pip-ephem-wheel-cache-tcrdvsnu/wheels/3b/bb/4f/1cac0cbc50558d501b6046fb2942596ca9004b1055553856b8
#10 236.9   Building wheel for wrapt (setup.py): started
#10 237.7   Building wheel for wrapt (setup.py): finished with status 'done'
#10 237.7   Created wheel for wrapt: filename=wrapt-1.12.1-cp39-cp39-linux_x86_64.whl size=33645 sha256=28875fea2bcb89331bc9d83ca89365f0dd64e00764711e553e670e200671c6eb
#10 237.7   Stored in directory: /tmp/pip-ephem-wheel-cache-tcrdvsnu/wheels/98/23/68/efe259aaca055e93b08e74fbe512819c69a2155c11ba3c0f10
#10 237.7 Successfully built PyYAML robotframework-ftplibrary robotframework-pabot robotframework-sshlibrary future bcrypt cffi pynacl wrapt
#10 237.7 Failed to build cryptography
#10 237.7 ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
#10 237.9 WARNING: You are using pip version 20.3.1; however, version 21.0.1 is available.
#10 237.9 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

**To Reproduce**
run docker build -t=[tag_name] [path_to_docker_file]

**Expected behavior**
Image built with no issues

**Robot template**

**Screenshots**

**Please provide any relevant information, such as:**
 - OS: Docker Desktop on Windows

**Additional context**

**Comment by linh-ngophuochoai** [comment]
I did further test and found that if remove g++  from Docker file, then there is not issue. Adding g++ will throw error as provided

**Comment by UltimateDogg** [comment]
yeah looks like they added rust requirements, can you make a pull and we can confirm image builds?

**Comment by linh-ngophuochoai** [comment]
Hi, created pull request https://github.com/ppodgorsek/docker-robot-framework/pull/332

**Comment by ppodgorsek** [comment]
The whitespace issue has been adjusted and the PR has been merged.
Thank you @linh-ngophuochoai for your contribution! :)
