### ISSUE TITLE
Question about permissions with local dir

### ISSUE THREAD

**Issue by luigikitten** [ppodgorsek/docker-robot-framework#333]
Hi,
     i am trying to use this image and I get a permission denied error: running on my jenkins machinem I wrote:

```
sh "mkdir robot-reports"
sh "docker run --shm-size=1g -e BROWSER=chrome -v $WORKSPACE/src/:/opt/robotframework/tests:Z -v $WORKSPACE/robot-reports:/opt/robotframework/reports:Z ppodgorsek/robot-framework:latest"
```

(tests are located in src folder), and I get:
```
[Pipeline] sh
+ docker run --shm-size=1g -e BROWSER=chrome -v /usr/share/jenkins-worker/workspace/ices_prod_monitoring_master/src/:/opt/robotframework/tests:Z -v /usr/share/jenkins-worker/workspace/ices_prod_monitoring_master/robot-reports:/opt/robotframework/reports:Z ppodgorsek/robot-framework:latest
[ ERROR ] Reading directory '/opt/robotframework/tests' failed: PermissionError: [Errno 13] Permission denied: '/opt/robotframework/tests'

Try --help for usage information.
[Pipeline] }

```
I have spent already few hours trying to understand what's going on but without success....
The $WORKSPACE folder is fine (i.e. from jenkins I can read/write everything).
Docker version reports:
```Pipeline] sh
+ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64
 Experimental:    false

```

do you have any suggestion? thanks!

**Comment by ppodgorsek** [comment]
Hi @luigikitten 

The README states:

> By default, containers are implicitly run using --user=1000:1000, please remember to adjust that command-line setting accordingly, for example:

    docker run \
        --user=1001:1001 \
        ppodgorsek/robot-framework:latest

> Remember that that UID/GID should be allowed to access the mounted volumes in order to read the test suites and to write the output.

Which user owns your "robot-reports" folder? What is the UID/GID of that owner?

**Comment by luigikitten** [comment]
Hi,
    many thanks for the reply! I have changed jenkins as follows:

```
sh "id"              
sh "ls -altrh"
sh "docker run --shm-size=1g -e BROWSER=chrome --user \$(id -u):\$(id -g) -v $WORKSPACE/src/:/opt/robotframework/tests:Z -v $WORKSPACE/robot-reports:/opt/robotframework/reports:Z ppodgorsek/robot-framework:latest" 

```

I still get errors:
```
+ id
uid=27313(502731363) gid=10008(Domain Users) groups=10008(Domain Users),393(dockerroot),1006(docker)
[Pipeline] sh
+ mkdir -p robot-reports
[Pipeline] sh
+ ls -altrh
total 80K
-rw-r--r--.   1 502731363 Domain Users   23 Mar  9  2020 README.md
-rw-r--r--.   1 502731363 Domain Users   39 Mar  9  2020 .gitignore
-rw-r--r--.   1 502731363 Domain Users  270 Mar  1 15:43 requirements.txt
drwxr-xr-x. 226 502731363 Domain Users  56K Mar  1 20:34 ..
drwxr-xr-x.   2 502731363 Domain Users   35 Mar  2 09:01 src
drwxr-xr-x.   2 502731363 Domain Users    6 Mar  2 13:07 robot-reports
-rw-r--r--.   1 502731363 Domain Users  551 Mar  2 13:31 Dockerfile
-rw-r--r--.   1 502731363 Domain Users 3.2K Mar  2 13:33 Jenkinsfile
drwxr-xr-x.   8 502731363 Domain Users  162 Mar  2 13:33 .git
drwxrwxrwx.   5 502731363 Domain Users  146 Mar  2 13:33 .
[Pipeline] sh
++ id -u
++ id -g
+ docker run --shm-size=1g -e BROWSER=chrome --user 27313:10008 -v /usr/share/jenkins-worker/workspace/ices_prod_monitoring_master/src/:/opt/robotframework/tests:Z -v /usr/share/jenkins-worker/workspace/ices_prod_monitoring_master/robot-reports:/opt/robotframework/reports:Z ppodgorsek/robot-framework:latest
[ ERROR ] Reading directory '/opt/robotframework/tests' failed: PermissionError: [Errno 13] Permission denied: '/opt/robotframework/tests'

```
many thanks again
Luigi

**Comment by ppodgorsek** [comment]
Actually, I misread your issue: the problem does not come from the reports folder but, rather, from your test folder (`/usr/share/jenkins-worker/workspace/ices_prod_monitoring_master/src/`).

What are the permissions of that folder?

**Comment by luigikitten** [comment]
Ciao,
    from the output above:

drwxr-xr-x.   2 502731363 Domain Users   35 Mar  2 09:01 src

that seems correct to me...

**Comment by ppodgorsek** [comment]
Hi Luigi,

Thanks, I missed that.
It's really strange. Would it be possible to change the owner of the folder to `1000:1000` before running the image with the default user please? This could indicate whether there is a bug in the way users are switched in the image or not.

Also, is SELinux enabled on the host?

Paul

**Comment by luigikitten** [comment]
Ciao,
    doing a chown 1000:1000 is not working here because user 1000:1000 is not available on this host...
The selinux hint is very interesting: getenforce reports "Enforcing"

any ideas? the :Z should already take care of selinux labelingf if I remember well..

**Comment by ppodgorsek** [comment]
SELinux does not like containers writing in `/etc`, `/home` and `/usr`. (reading seems to be fine)
The `:Z` option should indeed take care of the relabeling but one possibility could be that SELinux support is not enabled on Docker itself.

Could you check if it is enabled on Docker please?

    docker info | grep 'Security Options'

A useful resource for Docker and SELinux: https://jaosorior.dev/2018/selinux-and-docker-notes/

**Comment by luigikitten** [comment]
Hi,
   following your suggestion on /usr (where the jenkins shared disk is mounted in my case)  I have modified my jenkins script in order to copy everything in temporary directory (created via mktemp), run docker, and copy back the needed files.
Now it works nicely 👍 

Many thanks for the assistance, much appreciated!
