### ISSUE TITLE
Support for RF 4.0

### ISSUE THREAD

**Issue by zied-cision** [ppodgorsek/docker-robot-framework#334]
**Describe the bug**
Our tests are failing with the new RF4 syntax using this docker image

**To Reproduce**
1. Use at least one new IF statement syntax on your tests
2. Run the tests with from this image

**Expected behavior**
Test should run as expected

**Robot template**
```
IF    ${status}
            Log    Yes
ELSE
            Fail
END
```

**Please provide any relevant information, such as:**
 - RF 4.0
 - docker-robot-framework:latest

**Comment by ppodgorsek** [comment]
A new release (3.8.0) has been made, this is the last release based on Robot Framework 3.
The master branch has been upgraded to Robot Framework 4.
