### ISSUE TITLE
Is there any chance you can add Browser library?

### ISSUE THREAD

**Issue by ArielDabk** [ppodgorsek/docker-robot-framework#344]
**Is your feature request related to a problem? Please describe.**
Robot Framework deserves a browser automation solution that's designed for the 2020s.

Browser library powered by Playwright provides.

🚀 Speed, ✅ reliability and 🔬 visibility.

Conscise assertions.
Precise and fast browser window and tab control.
Chainable selector strategies.
Good shadow DOM support.
Easy mobile device descriptors.
Sending HTTP requests.

**Describe the solution you'd like**
https://robotframework-browser.org/

**Describe alternatives you've considered**
at this moment there is Selenium Library but i think it will be replaced by this library in the future

**Additional context**
That was number one of topics on ROBOCON2021

**Comment by crayfishuk** [comment]
Yep +1 from me. Browser/playwright deserves to be the default - if not included as standard...

**Comment by ppodgorsek** [comment]
The Browser library has been added. Selenium however remains the main focus for now, given its wider adoption in enterprise setups.
