### ISSUE TITLE
Docker will not build

### ISSUE THREAD

**Issue by acdbrn69** [ppodgorsek/docker-robot-framework#350]
**Describe the bug**
On Centos 7 I clone the repository and run 'sudo docker build --no-cache -t acdbrn/robot . after a while it ends and my docker is not there 

REPOSITORY   TAG                IMAGE ID       CREATED        SIZE
<none>       <none>             ad6636b548b3   2 days ago     46.2MB
<none>       <none>             d295081af7f4   2 days ago     46.2MB
<none>       <none>             71863819ebd8   2 days ago     46.2MB
<none>       <none>             22eb3c210f7e   2 days ago     46.2MB
python       3.9.0-alpine3.12   c0c46556c6d3   4 months ago   46.2MB

**To Reproduce**
1. clone repository
2. issue command sudo docker build --no-cache -t acdbrn/robot . 

**Expected behavior**
Docker should complete and see new docker in ls

**Please provide any relevant information, such as:**
 - OS: Centos 7

[build.log](https://github.com/ppodgorsek/docker-robot-framework/files/6258518/build.log)

**Comment by ppodgorsek** [comment]
Thank you for submitting the issue. Could you provide more information about what error appears in your build logs please?
The `build.log` file you attached does not contain any errors (it seems to be truncated) and I cannot reproduce this issue locally either.

**Comment by acdbrn69** [comment]
I am running CentOS Linux release 8.3.2011

Last metadata expiration check: 0:59:45 ago on Tue 06 Apr 2021 10:50:35 AM MDT.
Installed Packages
Name         : docker-ce
Epoch        : 3
Version      : 20.10.5
Release      : 3.el8
Architecture : x86_64
Size         : 115 M
Source       : docker-ce-20.10.5-3.el8.src.rpm
Repository   : @System
From repo    : docker-ce-stable
Summary      : The open-source application container engine
URL          : https://www.docker.com
License      : ASL 2.0
Description  : Docker is a product for you to build, ship and run any application as a
             : lightweight container.
             : 
             : Docker containers are both hardware-agnostic and platform-agnostic. This means
             : they can run anywhere, from your laptop to the largest cloud compute instance and
             : everything in between - and they don't require you to use a particular
             : language, framework or packaging system. That makes them great building blocks
             : for deploying and scaling web apps, databases, and backend services without
             : depending on a particular stack or provider.


This is the odd thing I do not see an error either but when I do a:
sudo docker image ls 
I do not see a new docker image

[admin@Robot-Docker docker-robot-framework]$ sudo docker image ls
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

Then I run
[admin@Robot-Docker docker-robot-framework]$ sudo docker build .

and get a warning:

Sending build context to Docker daemon  22.02kB
[WARNING]: Empty continuation line found in:
    RUN apk update   && apk --no-cache upgrade   && apk --no-cache --virtual .build-deps add     cargo     rust     gcc     g++     libffi-dev     linux-headers     make     musl-dev     openssl-dev     which     wget   && apk --no-cache add     "chromium~$CHROMIUM_VERSION"     "chromium-chromedriver~$CHROMIUM_VERSION"     "firefox-esr~$FIREFOX_VERSION"     nodejs     nodejs-npm     xauth     tzdata     "xvfb-run~$XVFB_VERSION"   && mv /usr/lib/chromium/chrome /usr/lib/chromium/chrome-original   && ln -sfv /opt/robotframework/bin/chromium-browser /usr/lib/chromium/chrome   && pip3 install     --no-cache-dir     robotframework==$ROBOT_FRAMEWORK_VERSION     robotframework-browser==$BROWSER_LIBRARY_VERSION     robotframework-databaselibrary==$DATABASE_LIBRARY_VERSION     robotframework-datadriver==$DATADRIVER_VERSION     robotframework-datadriver[XLS]     robotframework-datetime-tz==$DATETIMETZ_VERSION     robotframework-faker==$FAKER_VERSION     robotframework-ftplibrary==$FTP_LIBRARY_VERSION     robotframework-imaplibrary2==$IMAP_LIBRARY_VERSION     robotframework-pabot==$PABOT_VERSION     robotframework-requests==$REQUESTS_VERSION     robotframework-seleniumlibrary==$SELENIUM_LIBRARY_VERSION     robotframework-sshlibrary==$SSH_LIBRARY_VERSION     axe-selenium-python==$AXE_SELENIUM_LIBRARY_VERSION     PyYAML     awscli==$AWS_CLI_VERSION   && rfbrowser init   && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub     && wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$ALPINE_GLIBC/glibc-$ALPINE_GLIBC.apk"     && wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$ALPINE_GLIBC/glibc-bin-$ALPINE_GLIBC.apk"     && apk add glibc-$ALPINE_GLIBC.apk     && apk add glibc-bin-$ALPINE_GLIBC.apk     && rm glibc-$ALPINE_GLIBC.apk     && rm glibc-bin-$ALPINE_GLIBC.apk     && rm /etc/apk/keys/sgerrand.rsa.pub   && wget -q "https://github.com/mozilla/geckodriver/releases/download/$GECKO_DRIVER_VERSION/geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz"     && tar xzf geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz     && mkdir -p /opt/robotframework/drivers/     && mv geckodriver /opt/robotframework/drivers/geckodriver     && rm geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz   && apk del --no-cache --update-cache .build-deps
[WARNING]: Empty continuation lines will become errors in a future release.


Then it runs and I get:

rfbrowser init completed
The command '/bin/sh -c apk update   && apk --no-cache upgrade   && apk --no-cache --virtual .build-deps add     cargo     rust     gcc     g++     libffi-dev     linux-headers     make     musl-dev     openssl-dev     which     wget   && apk --no-cache add     "chromium~$CHROMIUM_VERSION"     "chromium-chromedriver~$CHROMIUM_VERSION"     "firefox-esr~$FIREFOX_VERSION"     nodejs     nodejs-npm     xauth     tzdata     "xvfb-run~$XVFB_VERSION"   && mv /usr/lib/chromium/chrome /usr/lib/chromium/chrome-original   && ln -sfv /opt/robotframework/bin/chromium-browser /usr/lib/chromium/chrome   && pip3 install     --no-cache-dir     robotframework==$ROBOT_FRAMEWORK_VERSION     robotframework-browser==$BROWSER_LIBRARY_VERSION     robotframework-databaselibrary==$DATABASE_LIBRARY_VERSION     robotframework-datadriver==$DATADRIVER_VERSION     robotframework-datadriver[XLS]     robotframework-datetime-tz==$DATETIMETZ_VERSION     robotframework-faker==$FAKER_VERSION     robotframework-ftplibrary==$FTP_LIBRARY_VERSION     robotframework-imaplibrary2==$IMAP_LIBRARY_VERSION     robotframework-pabot==$PABOT_VERSION     robotframework-requests==$REQUESTS_VERSION     robotframework-seleniumlibrary==$SELENIUM_LIBRARY_VERSION     robotframework-sshlibrary==$SSH_LIBRARY_VERSION     axe-selenium-python==$AXE_SELENIUM_LIBRARY_VERSION     PyYAML     awscli==$AWS_CLI_VERSION   && rfbrowser init   && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub     && wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$ALPINE_GLIBC/glibc-$ALPINE_GLIBC.apk"     && wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$ALPINE_GLIBC/glibc-bin-$ALPINE_GLIBC.apk"     && apk add glibc-$ALPINE_GLIBC.apk     && apk add glibc-bin-$ALPINE_GLIBC.apk     && rm glibc-$ALPINE_GLIBC.apk     && rm glibc-bin-$ALPINE_GLIBC.apk     && rm /etc/apk/keys/sgerrand.rsa.pub   && wget -q "https://github.com/mozilla/geckodriver/releases/download/$GECKO_DRIVER_VERSION/geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz"     && tar xzf geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz     && mkdir -p /opt/robotframework/drivers/     && mv geckodriver /opt/robotframework/drivers/geckodriver     && rm geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz   && apk del --no-cache --update-cache .build-deps' returned a non-zero code: 5

and if I do and Docker image ls I get this

[admin@Robot-Docker docker-robot-framework]$ sudo docker image ls
[sudo] password for admin: 
REPOSITORY   TAG                IMAGE ID       CREATED          SIZE
<none>       <none>             418f5b434e5e   53 minutes ago   46.2MB
python       3.9.0-alpine3.12   c0c46556c6d3   4 months ago     46.2MB
[admin@Robot-Docker docker-robot-framework]$

**Comment by acdbrn69** [comment]
I also ran the build in windows and git this:

**executor failed running [/bin/sh -c apk update   && apk --no-cache upgrade**   && apk --no-cache --virtual .build-deps add     cargo     rust     gcc     g++     libffi-dev     linux-headers     make     musl-dev     openssl-dev     which     wget   && apk --no-cache add     "chromium~$CHROMIUM_VERSION"     "chromium-chromedriver~$CHROMIUM_VERSION"     "firefox-esr~$FIREFOX_VERSION"     nodejs     nodejs-npm     xauth     tzdata     "xvfb-run~$XVFB_VERSION"   && mv /usr/lib/chromium/chrome /usr/lib/chromium/chrome-original   && ln -sfv /opt/robotframework/bin/chromium-browser /usr/lib/chromium/chrome   && pip3 install     --no-cache-dir     robotframework==$ROBOT_FRAMEWORK_VERSION     robotframework-browser==$BROWSER_LIBRARY_VERSION     robotframework-databaselibrary==$DATABASE_LIBRARY_VERSION     robotframework-datadriver==$DATADRIVER_VERSION     robotframework-datadriver[XLS]     robotframework-datetime-tz==$DATETIMETZ_VERSION     robotframework-faker==$FAKER_VERSION     robotframework-ftplibrary==$FTP_LIBRARY_VERSION     robotframework-imaplibrary2==$IMAP_LIBRARY_VERSION     robotframework-pabot==$PABOT_VERSION     robotframework-requests==$REQUESTS_VERSION     robotframework-seleniumlibrary==$SELENIUM_LIBRARY_VERSION     robotframework-sshlibrary==$SSH_LIBRARY_VERSION     axe-selenium-python==$AXE_SELENIUM_LIBRARY_VERSION     PyYAML     awscli==$AWS_CLI_VERSION   && rfbrowser init   && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub     && wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$ALPINE_GLIBC/glibc-$ALPINE_GLIBC.apk"     && wget -q "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$ALPINE_GLIBC/glibc-bin-$ALPINE_GLIBC.apk"     && apk add glibc-$ALPINE_GLIBC.apk     && apk add glibc-bin-$ALPINE_GLIBC.apk     && rm glibc-$ALPINE_GLIBC.apk     && rm glibc-bin-$ALPINE_GLIBC.apk     && rm /etc/apk/keys/sgerrand.rsa.pub   && wget -q "https://github.com/mozilla/geckodriver/releases/download/$GECKO_DRIVER_VERSION/geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz"     && tar xzf geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz     && mkdir -p /opt/robotframework/drivers/     && mv geckodriver /opt/robotframework/drivers/geckodriver     && rm geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz   && apk del --no-cache --update-cache .build-deps]: exit code: 5

**Comment by acdbrn69** [comment]
Looks like it is a network issue
