### ISSUE TITLE
Add support for Microsoft Edge

### ISSUE THREAD

**Issue by linh-ngophuochoai** [ppodgorsek/docker-robot-framework#352]
Hi Team,

I would like to request support for Microsoft Edge and Safari.

Those 2 two major browsers and the support will help with cross-browser testing.

Regards,

**Comment by UltimateDogg** [comment]
Safari is not on linux and edge is only a dev package thats beta and isnt built for alpine so i dont see how this could be added to this image

**Comment by linh-ngophuochoai** [comment]
Hi,

Thank you for the information. I have found the effort to test locally those browsers is outweigh the benefit. It turns out that just need to use BrowserStack to overcome this issue

**Comment by ppodgorsek** [comment]
This ticket was broken in two parts in order to better track those individual features. See  issue #401 for the Safari support.

**Comment by yuki-s0111** [comment]
Hi Team, 
I have made it work on the latest version of edge using webdriver for this Issue,
Can I create a PR?
The previous one was rejected by the test.
