### ISSUE TITLE
Got error "[ ERROR ] Suite 'Tests' contains no tests or tasks." when running docker run in CircleCi

### ISSUE THREAD

**Issue by yono-oy** [ppodgorsek/docker-robot-framework#354]
Hi.

I just ran with the following code in CircleCi and I got the error `[ ERROR ] Suite 'Tests' contains no tests or tasks.`.

docker run \
                --volume=/home/circleci/project/landingpage/Personal/Results:/opt/robotframework/reports:Z \
                --volume=/home/circleci/project/landingpage/Personal/TestCases:/opt/robotframework/tests:Z \
                -e BROWSER=chrome \
                ppodgorsek/robot-framework:latest

Actually, in my **landingpage/Personal/TestCases** there is a **check-product-consumerapp.robot**, this file is actually a test file. When I run `realpath check-product-consumerapp.robot` command in CircleCI, the result gives me the full path: /home/circleci/project/landingpage/Personal/TestCases.

In my laptop directory:
webautomation
|___ landingpage
|______ Personal
|___________ Resources
|___________ Results
|___________ TestCases
|________________ check-product-consumerapp.robot

And in CircleCI it becomes: /home/circleci/project/landingpage/Personal/TestCases

My **check-product-consumerapp.robot** looks like this:
*** Settings ***
Documentation   This test case check menu Product/Consumer App content body.

Library         SeleniumLibrary
Library         OperatingSystem

Resource        ../Resources/Keyword/default.robot
Resource        ../Resources/Keyword/product-consumerapp.robot
Resource        ../Resources/variables.robot

Test Setup      Open Web
Test Teardown   Exit Browser

*** Test Cases ***
Check Consumer App Content
    Go to Consumer App Page
    Check Consumer App Content
    Check Consumer App Downloads

Any idea of this? Thank you.

**Comment by ppodgorsek** [comment]
Hi @yono-oy , Sorry for the delayed reply.

It looks like your test case is trying to load resources from the `../Resources/` path.
Unfortunately, as this is a mounted volume, it is equivalent to Robot Framework trying to look into `/opt/robotframework/Resources/`, which doesn't exist.

I would suggest that you also mount this `../Resources/` on the command line.

**Comment by rivaldoeno** [comment]
I have the same problem.

I've a Jenkins in a docker and I want use run docker with Robot from Jenkins.

On Jenkins start I map this volume:
docker run --name jenkins-blueocean --rm --detach \
..
..
 --volume /home/robot/reports:/var/jenkins_home/workspace/prueba-RobotConDocker/reports:Z \
 --volume /home/robot/suites:/var/jenkins_home/workspace/prueba-RobotConDocker/tests:Z \
  myjenkins-blueocean:1.1

Inside the Jenkins image I can see the two directories /test and /reports and your content(with a helow word Robot test). But when I try execute Robot inside de Jenkins image there is an error:
$ docker run --shm-size=1g -v /var/jenkins_home/workspace/prueba-RobotConDocker/tests:/opt/robotframework/tests:Z -v /var/jenkins_home/workspace/prueba-RobotConDocker/reports:/opt/robotframework/reports:Z ppodgorsek/robot-framework:latest
[ ERROR ] Suite 'Tests' contains no tests or tasks.


The file content:
jenkins@21356004693e:/$ more /var/jenkins_home/workspace/prueba-RobotConDocker/tests/first_teste.robot
*** Test Cases ***

My First Robot Test
    Log To Console            Hello Robot World!

This test works fine when I call this test from the server where Jenkins is runing. Inside the Jenkins pipeline I execute a ls command to check if is privilege, but the ls also works:
+ ls /var/jenkins_home/workspace/prueba-RobotConDocker/tests
first_teste.robot

+ touch /var/jenkins_home/workspace/prueba-RobotConDocker/tests

@yono-oy or @ppodgorsek, do You know what I am doing wrong?

**Comment by ppodgorsek** [comment]
Closing this ticket due to lack of activity.
