### ISSUE TITLE
Pabot grouping in --ordering option is not working correctly

### ISSUE THREAD

**Issue by DKryczka** [ppodgorsek/docker-robot-framework#356]
**Describe the bug**
After setting up test suites to groups using {}, group tests are not running, only parallel tests in random order.

**To Reproduce**
1. Create order.txt file which contains:
{
--suite Test-Cases.Test1
--suite Test-Cases.Test2
--suite Test-Cases.Test3
}
{
--suite Test-Cases.Test4
--suite Test-Cases.Test5
}
2. Run Tests
sudo docker run --shm-size=1g \
    -v ${path}:/opt/robotframework/reports:Z \
    -v ${path}:/opt/robotframework/tests:Z \
    -e ROBOT_THREADS=2 \
    -e BROWSER=headlesschrome \
    -e PABOT_OPTIONS="--ordering /opt/robotframework/tests/order.txt" \
    ppodgorsek/robot-framework:latest

**Expected behavior**
It should run group tests, each thread should run single group

**Please provide any relevant information, such as:**
 - MacOS / Linux 
 - Browser Chromium/Firefox latest versions
- Im using Browser Library 
- I run tests locally using pabot v2.0 with same order.txt file and group tests are working good. Maybe there is a problem with old pabot version and updating it to 2.0 on docker will fix issue?

**Comment by ppodgorsek** [comment]
Hi @DKryczka , thank you for reporting this issue.
The Pabot library has been upgraded today and is in the latest image, could you try again please?
If it still doesn't work, I would suggest you open a bug report within [the Pabot project](https://github.com/mkorpela/pabot), as this seems to be a bug on their side.
