### ISSUE TITLE
Support for robotframework-zoomba

### ISSUE THREAD

**Issue by AmitKulkarni9** [ppodgorsek/docker-robot-framework#357]
Hi,

Will it be possible to add Robotframework-Zoomba Library support?
This will increase opportunity to test  GUI, REST API, SOAP API, automation inside the container using this library.

Zoomba is a collection of libraries spanning GUI, REST API, SOAP API, Mobile, and Windows Desktop automation using Robot Framework. These libraries are extensions of existing libraries SeleniumLibrary, Requests, SudsLibrary, and AppiumLibrary.

Thank you

**Comment by ppodgorsek** [comment]
The feature allowing to dynamically install additional dependencies has finally been implemented as part of #376 and the details can be found in the README: https://github.com/ppodgorsek/docker-robot-framework#installing-additional-dependencies
