### ISSUE TITLE
Upgrade robotframework-databaselibrary from 1.2 to 1.2.4 to solve errors on 'Execute Sql Script'

### ISSUE THREAD

**Issue by MacNetron** [ppodgorsek/docker-robot-framework#358]
**Describe the bug**
While running a test with the `Library  DatabaseLibrary`, using the keyword `Execute Sql Script  ${RESOURCES_DIR}/my-script.sql`, I ran into the error `TypeError: unsupported operand type(s) for +: 'int' and 'Cursor' `.

On the DatabaseLibrary, I found this closed issue: https://github.com/franz-see/Robotframework-Database-Library/issues/113
Which describes that the issue is solved in 1.2.1.

So I've expanded my own Dockerfile to use the current version 1.2.2:
```
FROM ppodgorsek/robot-framework:latest
<snip>
RUN pip3 install robotframework-databaselibrary==1.2.2
```
And now everything runs fine indeed.

So please update robotframework-databaselibrary from 1.2 to 1.2.2.
And keep up the good work, genuinely happy with this project!!

**Comment by ppodgorsek** [comment]
Thank you for the bug report and the nice comment, @MacNetron ! I'd glad you are enjoying the project :)
The library has been upgraded and Docker Hub has built a new "latest" image, your issue should therefore be resolved.
