### ISSUE TITLE
Add robotframework-lint library

### ISSUE THREAD

**Issue by sthiriet** [ppodgorsek/docker-robot-framework#359]
**Is your feature request related to a problem? Please describe.**
We use your image in our CI template and it would be great if we could lint our robot code before running it.

**Describe the solution you'd like**
add [robotframework-lint python package](https://pypi.org/project/robotframework-lint/) like described in this [comment](https://github.com/ppodgorsek/docker-robot-framework/issues/314#issuecomment-747442238)
 
If you agree, I can create a pull request.

**Comment by ppodgorsek** [comment]
The feature allowing to dynamically install additional dependencies has finally been implemented as part of #376 and the details can be found in the README: https://github.com/ppodgorsek/docker-robot-framework#installing-additional-dependencies

I would however question the need for any lint tool in this image as it was designed to run Robot Framework tests, while your linting use case seems more relevant as a previous separate step of your pipeline.

**Comment by ppodgorsek** [comment]
As mentioned above, linting should be handled separately. Closing this ticket due to inactivity.
