### ISSUE TITLE
i am facing no broser open issue

### ISSUE THREAD

**Issue by bindumadhav100** [ppodgorsek/docker-robot-framework#371]
i am uploading one file and upload from given location path is incorrect saying like below 
InvalidArgumentException: Message: invalid argument: File not found : FlexiBSC_220MB.zip
  (Session info: chrome=86.0.4240.111)
i am using robotframework 4.1 using is it will support to upload zip files please help me to solve this
and below is my screen shot 
![image](https://user-images.githubusercontent.com/90021984/131963333-29b44891-ffb8-40b1-84d9-919e63926f14.png)

**Comment by suyashsikarwar** [comment]
HI Bindu, you can close/delete this ticket. Mostly the file was not copied inside the container.

**Comment by BinduPython100** [comment]
ok suyash i am closing this ticket..i got the solution

**Comment by bindumadhav100** [comment]
closing this issue
