### ISSUE TITLE
Cannot install easily custom libraries

### ISSUE THREAD

**Issue by lucagiove** [ppodgorsek/docker-robot-framework#376]
**Describe the bug**

**To Reproduce**
1. Add a new library in requirements
2. Run the container and tests

**Expected behavior**
I would expect the container to install dependencies from outside like requirements.txt or similar

**Comment by ppodgorsek** [comment]
@lucagiove Thank you for your very useful suggestion! It took a while but this feature has finally been implemented and the details can be found in the README.
