### ISSUE TITLE
Update Browser Library to latest version(11.3)

### ISSUE THREAD

**Issue by DKryczka** [ppodgorsek/docker-robot-framework#380]
**Is your feature request related to a problem? Please describe.**
Latest version of Browser library contains a lot of bug fixes and its more stable version.
Current library version has plenty of bugs

**Describe the solution you'd like**
I would like to update library with browser binaries to latest version(11.3)

Install Browser library from [PyPi](https://pypi.org/search/?q=robotframework-browser) with pip:
> `pip install --upgrade robotframework-browser`
Clean old browser binaries and node dependecies:
> `rfbrowser clean-node`
Initialize the Browser library with new node dependecies:
> `rfbrowser init`

If it still doesn't work please use: `npx playwright install`

**Additional context**
1. I would like to ask if it's possible to check library update on separate branch, just to make sure it works good? 
2. Is it possible in case of any problems to revert changes to existing 6.0 version?

3. In case of any problems with locators with latest library version it's recommended to set `strict=False` in library import as it is set to `True` by default.

**Comment by ppodgorsek** [comment]
This has been done as part of issue #386.
