### ISSUE TITLE
need library 'RPA.Archive' build together with docker image

### ISSUE THREAD

**Issue by lovelyplanet2019** [ppodgorsek/docker-robot-framework#406]
I have a script that use 'RPA.Archive'. 
the docker cannot run with error missing library.
Can I request to have the library bundled with docker image?

else, please advice how do I build the image myself by adding the additional library?

[ ERROR ] Error in file '/opt/robotframework/tests/BrowserFunctions.robot' on line 11: Importing library 'RPA.Archive' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):

**Comment by ElHoussin1** [comment]
Hello, did you find the solution to this issue ?

**Comment by ppodgorsek** [comment]
The feature allowing to dynamically install additional dependencies has finally been implemented as part of #376 and the details can be found in the README.
