### ISSUE TITLE
Add tag to the latest version

### ISSUE THREAD

**Issue by StephanMath** [ppodgorsek/docker-robot-framework#409]
**Is your feature request related to a problem? Please describe.**
In my Gitlab environment, docker-hadolint failed with error : 
"Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag"

**Describe the solution you'd like**
To remove lint error could you pin the version explicitly to a release tag, instead of "latest" ?

**Describe alternatives you've considered**
Actually i skip this error with rule "allow_failure: true" for docker-hadolint in my gitlab-ci, but this solution is unavailable for all stages.

**Comment by ppodgorsek** [comment]
Good point, releases are usually made on a regular basis according to dependency upgrades.
I upgraded the dependencies today and published version 5.0.0.
