### ISSUE TITLE
Allow /home directory for user in base image

### ISSUE THREAD

**Issue by hajdukd** [ppodgorsek/docker-robot-framework#410]
**Is your feature request related to a problem? Please describe.**
I know that dependencies should be built into base image, but for development purposes its sometimes useful to allow install of dependencies for 1000 user. Home directory is required for that.

**Describe the solution you'd like**
Please add 1000 user and group as regular named user and groups.

**Describe alternatives you've considered**
Bulding everything into the image, which is not really developer friendly.

**Additional context**
N/A

**Comment by ppodgorsek** [comment]
If you need to install dependencies during runtime, the best practice would be to mount a volume, in which the dependencies will be installed. This will avoid those dependencies having to be downloaded every time, hence speeding up your pipeline.

You can change the user running the container with the `--user=1000:1000` command line argument.

**Comment by hajdukd** [comment]
Hi,
This won't work as volumes are not shared between CI runners nor runners that are spawned when needed. So you would install them on volume every time over and over. It's also highly dependent on the CI engine you are using.

ps. This feature is just a sugestion. One can always build own image with required changes. Feel free to close if you think it's a bad idea.

**Comment by ppodgorsek** [comment]
The feature allowing to dynamically install additional dependencies has finally been implemented as part of #376 and the details can be found in the README.
