### ISSUE TITLE
Bash warning when ROBOT_TEST_RUN_ID is set

### ISSUE THREAD

**Issue by dencze** [ppodgorsek/docker-robot-framework#421]
**Describe the bug**
Warning out of run-tests-in-virtual-screen.sh if ROBOT_TEST_RUN_ID is set
`/opt/robotframework/bin/run-tests-in-virtual-screen.sh: line 11: [: -eq: unary operator expected`

**To Reproduce**
1. Start docker with environment ROBOT_TEST_RUN_ID'
`docker run -e ROBOT_TEST_RUN_ID="local" ppodgorsek/robot-framework:latest`

**Expected behavior**
No warning out of bash script

**Robot template**
n/a

**Screenshots**
n/a

**Please provide any relevant information, such as:**
n/a

**Additional context**
n/a

**Comment by ppodgorsek** [comment]
Thanks for your contribution, @dencze ! I updated your PR and merged it a few moments ago.
