### ISSUE TITLE
Please add to documentation if Mac (M1/M2) and/or Raspberry Pi (ARM) are supported

### ISSUE THREAD

**Issue by rekcodocker** [ppodgorsek/docker-robot-framework#443]
**Is your feature request related to a problem? Please describe.**
I can't find in the Readme.md if this should work on a mac. I can find a reference to a Mac but at the same time the architecture seems to be AMD64 - so maybe it's only for the Intel generation of macs.  I can not tell.

**Preferred solution**
Please add to the documentation which architectures are or are not supported.

**Comment by ppodgorsek** [comment]
Docker Hub already states that this is an linux/amd64 image.
Could you let me know if this works on the devices you are mentioning please?

**Comment by rekcodocker** [comment]
I plan to use it on a Mac with a new M1 or M2 processor. But I can't find if it works or if it can be built.

If it can't - that's fine.  But I just could not find out one way or another from reading the documentation.
I can imagine it is hard if the image depends on binaries from Chrome and Firefox.

My suggestion is a simple "Does not build on Mac M1" added to the Readme.md (if that is indeed the case).

**Comment by ppodgorsek** [comment]
A 5-minute online search revealed that ARM-based devices cannot run linux/amd64 images...

I added explanations in the troubleshooting section of the README. (see PR #451)

I also created a separate enhancement to build and push images for multiple architectures, rather than only linux/amd64. (see #455)
