### ISSUE TITLE
WebDriverException: Chrome DevTools Disconnected Error on Capture Page Screenshot in GitHub Actions using ppodgorsek/robot-framework:latest

### ISSUE THREAD

**Issue by IshanChakrabortyYT** [ppodgorsek/docker-robot-framework#506]
**Describe the bug**
Encountering an error while running Robot Framework tests on GitHub Actions using the ppodgorsek/robot-framework:latest Docker image. The error appears specifically during the Capture Page Screenshot keyword execution, indicating a disconnection from Chrome DevTools.

```
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=126.0.6478.126)
Stacktrace:
#0 0x558c86590c7a <unknown>
#1 0x558c86273e2c <unknown>
#2 0x558c862598f8 <unknown>
#3 0x558c862597d3 <unknown>
#4 0x558c86276232 <unknown>
#5 0x558c86301ccc <unknown>
#6 0x558c862e3363 <unknown>
#7 0x558c862b3247 <unknown>
#8 0x558c862b3b9e <unknown>
#9 0x558c8655724b <unknown>
#10 0x558c8655b2f1 <unknown>
#11 0x558c86542afe <unknown>
#12 0x558c8655be52 <unknown>
#13 0x558c8652779f <unknown>
#14 0x558c86580638 <unknown>
#15 0x558c86580810 <unknown>
#16 0x558c8658fdac <unknown>
#17 0x7f8cbc13f507 start_thread
#18 0x7f8cbc1c3214 __GI___clone
| FAIL |
WebDriverException: Message: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=126.0.6478.126)
Stacktrace:
#0 0x558c86590c7a <unknown>
#1 0x558c86273e2c <unknown>
#2 0x558c8625a037 <unknown>
#3 0x558c86259fb5 <unknown>
#4 0x558c86258999 <unknown>
#5 0x558c8625933f <unknown>
#6 0x558c86277475 <unknown>
#7 0x558c86277e10 <unknown>
#8 0x558c8627b2e5 <unknown>
#9 0x558c8627b36c <unknown>
#10 0x558c862c021e <unknown>
#11 0x558c862c0751 <unknown>
#12 0x558c86304fa1 <unknown>
#13 0x558c862e35ed <unknown>
#14 0x558c86302303 <unknown>
#15 0x558c862e3363 <unknown>
#16 0x558c862b3247 <unknown>
#17 0x558c862b3b9e <unknown>
#18 0x558c8655724b <unknown>
#19 0x558c8655b2f1 <unknown>
#20 0x558c86542afe <unknown>
#21 0x558c8655be52 <unknown>
#22 0x558c8652779f <unknown>
#23 0x558c86580638 <unknown>
#24 0x558c86580810 <unknown>
#25 0x558c8658fdac <unknown>
#26 0x7f8cbc13f507 start_thread
#27 0x7f8cbc1c3214 __GI___clone
```

**To Reproduce**
1- Set up GitHub Actions Workflow:
  - Create a GitHub Actions workflow file (e.g., .github/workflows/robot_tests.yml).
  - Configure the workflow to use the ppodgorsek/robot-framework:latest Docker image.
  - Define Robot Framework Test with Capture Page Screenshot Keyword:

2- Write a Robot Framework test that includes a failure condition to trigger Capture Page Screenshot.
```
*** Settings ***
Library    SeleniumLibrary

*** Test Cases ***
Sample Test Case
    Open Browser    https://example.com    chrome
    Capture Page Screenshot
    [Teardown]    Close All Browsers
```
3- Run the Workflow:
  - Trigger the GitHub Actions workflow that runs the Robot Framework test.

4- Observe Error:
  - When the test encounters a failure or attempts Capture Page Screenshot, observe the error logs in GitHub Actions output.

**Expected behavior**
Robot Framework should successfully capture the page screenshot upon failure without throwing a DevTools disconnection error.

**Robot template**
Any Robot template which could help reproduce the issue.

**Screenshots**

**Please provide any relevant information, such as:**
Environment:
Docker Image: ppodgorsek/robot-framework:latest
Chrome Version: 126.0.6478.126
Robot Framework Version: Latest (as per Docker image)
Running on: GitHub Actions

**Additional context**

**Comment by kitschyboy** [comment]
Issue reproduced on our side with ppodgorsek/robot-framework:7.2.0
We have a scheduled pipeline on a private GitlabCI instance, launched every 10 minutes : until yesterday 23h26 (French time), it worked perfectly, but 10 minutes later we have the following error repeteadly when Selenium tries to open a url :
![image](https://github.com/user-attachments/assets/ab99ac3b-319d-4b06-bf50-fc69cdaa893b)

Nothing is different between the successful runs and the following ones that fail (same docker image, same tests, same runner) : no clue for now regarding the origin of the problem.

**Comment by andy-kru** [comment]
I don't observe this issue any more after the dependencies update: https://github.com/ppodgorsek/docker-robot-framework/pull/507

**Comment by MohamedAAbdelwahab** [comment]
> I don't observe this issue any more after the dependencies update: #507

Thanks , you saved my life

**Comment by ppodgorsek** [comment]
The PR has been merged and the latest image has been updated on the Docker Hub. Closing this issue.
