### ISSUE TITLE
Automated update of dependencies in Dockerfile

### ISSUE THREAD

**Issue by ppodgorsek** [ppodgorsek/docker-robot-framework#54]
Investigate if Travis could also be used to update the versions of all dependencies and to commit an updated Dockerfile whenever it is possible (merged to master via an automated pull request merge).

This would allow to regularly push updated Docker images without the need for a manual intervention.

**Comment by christian-roggia** [comment]
You can capture the `tag event` with Travis CI and configure a bash script for pushing new images to the registry. Environment variables are usually used for authentication. You can do the same with the `push event` if you want to publish the **latest** image.
