### ISSUE TITLE
[ ERROR ] Suite 'Tests' contains no tests

### ISSUE THREAD

**Issue by dtnhoang** [ppodgorsek/docker-robot-framework#61]
Getting [ ERROR ] Suite 'Tests' contains no tests when trying to run the image and when specifying either browser.

Running Docker toolbox:
command:
docker run -v /Users/dthmacpro/Documents/robotfw/reports:/opt/robotframework/reports -v /Users/dthmacpro/Documents/robotfw/test_suites:/opt/robotframework/tests -e BROWSER=firefox ppodgorsek/robot-framework:latest
[ ERROR ] Suite 'Tests' contains no tests.

not sure why it's not seeing the Tests... please assist, thanks!

**Comment by ppodgorsek** [comment]
I like issues which are solved so quickly :)
Could you provide more details explaining what was causing the issue please? This will be helpful for  anyone having a similar problem in the future.

**Comment by balbinas** [comment]
I just had the same problem, was it solved? Thanks!
`
⇒  docker run -v `pwd`/reports:/opt/robotframework/reports:Z\
>     -v `pwd`/test:/opt/robotframework/tests:Z\
>     -e BROWSER=chrome\
>     ppodgorsek/robot-framework:latest
Unable to find image 'ppodgorsek/robot-framework:latest' locally
latest: Pulling from ppodgorsek/robot-framework
a8ee583972c2: Pull complete
ccadbbf21fba: Pull complete
43a21eed8472: Pull complete
189e6064fa8c: Pull complete
bae66e809115: Pull complete
223436a0300e: Pull complete
3a1a65a5708e: Pull complete
96bf5679c3a5: Pull complete
Digest: sha256:5ce624604f257012cdf53dca2f8cef86717e0769cf4b4bd056203b43a93ef6df
Status: Downloaded newer image for ppodgorsek/robot-framework:latest
[ ERROR ] Suite 'Tests' contains no tests.
`

**Comment by ppodgorsek** [comment]
Could you replace \`pwd\` by the full path and retry please?

**Comment by balbinas** [comment]
Oh okay that makes sense, I ran my tests in the correct path and they do run. I'm trying to run this in bitbucket and I'm having trouble with the chromedriver, still working on it. 
But thank you!!

**Comment by ppodgorsek** [comment]
Glad that it works by replacing `pwd` by the correct path. Out of curiosity, what OS are you using? I'd like to find an OS-independent command line if that's the problem.

**Comment by christian-roggia** [comment]
@ppodgorsek unfortunately, as far as I know, there is not OS-independent command for `PWD`, on Windows this is how the command line should look like:

> docker run -v ${PWD}/reports:/opt/robotframework/reports:Z -v ${PWD}/test:/opt/robotframework/tests:Z -e BROWSER=firefox ppodgorsek/robot-framework:latest

If you want to update the README you can add this command for Windows users.

**Comment by MilindDivre** [comment]
[ ERROR ] Suite 'Tests' contains no tests. how is this issue resolved

**Comment by ppodgorsek** [comment]
The README file has been updated with the information about how to run the tests on Windows.

**Comment by piotr-mazur** [comment]
Hi, I used:
docker run \
    -v /Users/znajduch/Documents/drobot/reports:/opt/robotframework/reports:Z \
    -v /Users/znajduch/Documents/drobot/test:/opt/robotframework/tests:Z \
    -e BROWSER=chrome \
    ppodgorsek/robot-framework:latest
[ ERROR ] Suite 'Tests' contains no tests.

Any tip

**Comment by ppodgorsek** [comment]
@piotr-mazur Aren't you missing an 's' in your local path?
/Users/znajduch/Documents/drobot/test**s**

**Comment by piotr-mazur** [comment]
docker run \
    -v /Users/znajduch/Documents/drobot/reports:/opt/robotframework/reports:Z \
    -v /Users/znajduch/Documents/drobot/tests:/opt/robotframework/tests:Z \
    -e BROWSER=chrome \
    ppodgorsek/robot-framework:latest
[ ERROR ] Suite 'Tests' contains no tests.

**Comment by ppodgorsek** [comment]
Sorry, my mistake, it is indeed /Users/znajduch/Documents/drobot/test
I assume drobot is the directory where you clone the project, right?

**Comment by piotr-mazur** [comment]
@ppodgorsek I just run it with the correct path and result is that same 
@dtnhoang  How you resolve that issue
 , because it looks like yours is similar

**Comment by piotr-mazur** [comment]
How to use docker-robot-framework:
1. Clone or Download a project form: https://github.com/ppodgorsek/docker-robot-framework to folder.
2. Add Full path to the folder where you download project if you want to run simply test instead 'pwd' 
3 You have to have project an all with docker instaled things

**Comment by piotr-mazur** [comment]
@ppodgorsek you can add something like that to avoid that kind funny questions 
and if I want to rum mine tests it should be also added to the files with repositories?

**Comment by humbienri** [comment]
@ppodgorsek Hi there!
Thank you very much for taking on this work/effort, first of all.  Now, would you rather I open a new issue regarding this same matter of "no tests" given that this one is closed already.  Actually, all "suite has not tests" issues are already closed yet that is the very same problem I am facing.

Please advise.  Yes I am using a Windows 10 host.

Thank you sir.

**Comment by ppodgorsek** [comment]
Hi @humbienri,

Could you open a new issue instead of commenting on old ones please?

In that new issue, please indicate the following information:
* What command line you are using?
* What is the outcome of following the "Troubleshooting" steps from the readme?

**Comment by PaneetFinance** [comment]
Hi I still face this issue and still not sure how to fix it by pwd.
I ran script by git action and it always return as below.
![Uploading Screenshot 2024-06-20 at 7.42.18 PM.png…]()
