### ISSUE TITLE
Add parallel execution support

### ISSUE THREAD

**Issue by christian-roggia** [ppodgorsek/docker-robot-framework#76]
[pabot](https://github.com/mkorpela/pabot) should be added to the toolchain of this chart. This would allow users to launch tests in parallel whenever it is required.

This can be done by passing environment variables to the docker container and invoking a bash script whenever required.

Internally we are currently using the following bash script:

```bash
#!/bin/sh

set -e

# Install parallel executor "pabot"
pip install --upgrade --quiet robotframework-pabot

# Set number of threads for parallel execution
RF_THREADS=4

# Launch Robot Framework instances
xvfb-run \
    --server-args="-screen 0 ${SCREEN_WIDTH}x${SCREEN_HEIGHT}x${SCREEN_COLOUR_DEPTH} -ac" \
    pabot \
        --verbose \
        --processes $RF_THREADS \
        --outputdir /opt/robotframework/reports \
        ${ROBOT_OPTIONS} \
        /opt/robotframework/tests

exit 0
```

**Comment by ppodgorsek** [comment]
This new feature has been added:
* The ROBOT_THREADS environment variable has been defined to control the parallelisation
* Pabot has been installed and is only used whenever needed
* A new section in the README file has been added to explain how to use it
* The automated tests have been updated
