### ISSUE TITLE
Outdated Chromium causes Docker build to fail

### ISSUE THREAD

**Issue by guangxuli** [ppodgorsek/docker-robot-framework#82]
Complete!
Last metadata expiration check: 0:00:57 ago on Tue Apr  3 08:35:14 2018.
No match for argument: chromedriver-63.0.*
No match for argument: chromium-63.0.*
**Error: Unable to find a match**
The command '/bin/sh -c dnf upgrade -y   && dnf install -y     chromedriver-$CHROMIUM_VERSION     chromium-$CHROMIUM_VERSION     firefox-$FIREFOX_VERSION     python2-pip-9.0.1-*     xauth     xorg-x11-server-Xvfb-1.19.*     which     wget   && dnf clean all' returned a non-zero code: 1

**Comment by ppodgorsek** [comment]
Fixed
