### ISSUE TITLE
Error: Suite 'Tests' contains no tests.

### ISSUE THREAD

**Issue by ascii84** [ppodgorsek/docker-robot-framework#90]
Hi,

When I try to run a test I get [Error] Suite 'Tests' contains no tests.
I've downloaded sources from GitHub and I'm in "C:\DockerTests\docker-robot-framework-master" folder and I run following command:
docker run \
    -v ${PWD}/reports:/opt/robotframework/reports:Z \
    -v ${PWD}/test:/opt/robotframework/tests:Z \
    -e BROWSER=chrome \
    ppodgorsek/robot-framework:latest

Any hint?

BR
Jakub

**Comment by ppodgorsek** [comment]
Hi Jakub,
Could you try again by replacing ${PWD} by the full path to your folder please?

**Comment by ascii84** [comment]
Hi,

Problem nas been resolved.
It turned out that tests must be in User folder

Br
Jakub

W dniu pt., 18.05.2018 o 19:11 Paul Podgorsek <notifications@github.com>
napisał(a):

**Comment by ppodgorsek** [comment]
Thanks for the info, I will add a part in the troubleshooting section with info to avoid such issues with permissions.

**Comment by ascii84** [comment]
Hi,
Just place tests in C:\Users\youruser\tests

Br
Jakub

W dniu śr., 20.06.2018 o 10:24 Martijn Bos <notifications@github.com>
napisał(a):

**Comment by martywoods** [comment]
Unfortunately this does not solve the problem for me.

**Comment by ppodgorsek** [comment]
@martywoods This error is usually related to permissions on the folder where the tests are located.
Have you tried checking the logs to see if they show any specific error message?

Could you also try running the tests with a full path instead of a relative one please?

**Comment by ppodgorsek** [comment]
The troubleshooting section of the README file has been updated with the above information.

**Comment by humbienri** [comment]
Hello again @ppodgorsek,

What do you mean by checking the logs, which logs? Where?  Or how to check those permissions you are mentioning.

I dislike the idea of moving my whole repo to the "Users" folder and just keep it closer to my C root drive.

**Comment by ppodgorsek** [comment]
As mentioned in the other ticket, please move your questions to a dedicated ticket.

**Comment by Nightlord851108** [comment]
@ppodgorsek 

Here just to provide a solution.

I just faced the same issue above, and I overcome the issue with the docker-compose tool.

docker-compose.yml: 
> version: "2"
> services:
>   keystonejs:
>     image: ntutselab/keystonejs
>     ports:
>      - "3000:3000"
>     links:
>      - mongodb
>   mongodb:
>     image: mongo
>     ports:
>      - "27017:27017"
>   robot:
>     image: ppodgorsek/robot-framework:3.5.0
>     depends_on:
>       - "keystonejs"
>       - "mongodb"
>     volumes:
>        - ./reports:/opt/robotframework/reports:Z
>        - ./tests:/opt/robotframework/tests:Z

With the docker-compose above, I'm able to use a related path, which makes more sense if I want to execute the test script on a CI server.

Hope this would help someone.
