### ISSUE TITLE
dnf install -y chromedriver-66.0.* Failed, No match for arguments.

### ISSUE THREAD

**Issue by qiangcui** [ppodgorsek/docker-robot-framework#93]
Complete!
Non-fatal <unknown> scriptlet failure in rpm package libgcc
Non-fatal <unknown> scriptlet failure in rpm package libgcc
Last metadata expiration check: 0:01:38 ago on Wed Jun 27 21:59:23 2018.
No match for argument: chromedriver-66.0.*
No match for argument: chromium-66.0.*
Error: Unable to find a match

**Comment by qiangcui** [comment]
Hello Paul.
I want to build the image by myself and I got above error said there is no matching version for chromedriver-66.0.*/63.0.* 
Do you have any idea about this?

**Comment by qiangcui** [comment]
I found I can install 65.0.* instead of 66.0.*. Can you install 66.0.*?

**Comment by qiangcui** [comment]
I also found I can install 67.0.* version too. It seems like only 65 and 67 version are downloadable except other versions.

**Comment by ppodgorsek** [comment]
This has been fixed by updating Chromium to version 67.0.
