### ISSUE TITLE
When building image '/opt/robotframework/drivers/': No such file or directory

### ISSUE THREAD

**Issue by rlembo06** [ppodgorsek/docker-robot-framework#97]
when I try to start docker build with :
` sudo docker build -t selenium-ci .`

it failed with :
`mkdir: cannot create directory '/opt/robotframework/drivers/': No such file or directory`

maybe pip should install robot framework in /opt/robotframework and it's not the case anymore ?

**Comment by ppodgorsek** [comment]
This is not related to pip, the folder is manually created (line 47 of the Dockerfile).
`/opt/robotframework` should have been created by the volume definition earlier in that file.

Which version of Docker are you using?

**Comment by ppodgorsek** [comment]
The Dockerfile has been updated to make sure that the parent folders exist too.
Could you retry please?

**Comment by ppodgorsek** [comment]
Closing this issue, as it cannot be reproduced anymore.
